const { SlashCommandBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const game = require('../pika-captcha');
const data = new SlashCommandBuilder().setName('captcha').setDescription('Play the fictional PikaCAPTCHA game');
function panel(s) {
  const rows = [];
  for (let row = 0; row < 3; row++) rows.push(new ActionRowBuilder().addComponents(...[0,1,2].map(col => { const n = row * 3 + col; return new ButtonBuilder().setCustomId(`cap_cell:${s.token}:${n}`).setLabel(s.cells[n]).setStyle(s.selected.includes(n) ? ButtonStyle.Primary : ButtonStyle.Secondary); })));
  rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`cap_verify:${s.token}`).setLabel('VERIFY').setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`cap_stats:${s.owner}`).setLabel('STATS').setStyle(ButtonStyle.Secondary)));
  return { content: '🤖 **PIKACAPTCHA**\n\nSelect every square containing 🐧 PikaPeng.', components: rows };
}
async function execute(i) { const u = await game.get(i.user.id); if (!u.owned) return i.reply({ content: '🤖 You do not own PikaCAPTCHA. Purchase it from /shop for 🐟 500.', ephemeral: true }); return i.reply({ ...panel(game.start(i.user.id)), ephemeral: true }); }
async function button(i) { const [action, token, value] = i.customId.split(':'); if (action === 'cap_stats') { const u = await game.get(token); return i.reply({ content: `🤖 PIKACAPTCHA STATS\nSolved: ${u.solved}\nFailed: ${u.failed}\nBest streak: ${u.bestStreak}\nCurrent streak: ${u.currentStreak}\nFastest solve: ${u.fastest === null ? '—' : `${u.fastest.toFixed(2)}s`}`, ephemeral: true }); } const s = game.session(token); if (!s || s.owner !== i.user.id) return i.reply({ content: 'This PikaCAPTCHA belongs to another user or has expired.', ephemeral: true }); if (action === 'cap_cell') { await game.toggle(token, Number(value)); return i.update(panel(game.session(token))); } const result = await game.verify(token); if (!result) return i.reply({ content: 'This PikaCAPTCHA has already been completed.', ephemeral: true }); return i.update({ content: result.ok ? `🤖 **VERIFICATION SUCCESSFUL**\n\nTime: ${result.elapsed.toFixed(2)}s\nStreak: ${result.streak}` : `🤖 **VERIFICATION FAILED**\n\nCorrect selections: ${result.correct}\nYour selections: ${result.selected}\n\nStreak reset to 0.`, components: [] }); }
module.exports = { data, execute, button, panel };
