const crypto = require('node:crypto');
const { SlashCommandBuilder, ModalBuilder, TextInputBuilder, TextInputStyle, ActionRowBuilder, EmbedBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const economy = require('../economy'); const config = require('../config'); const logger = require('../utils/logger');
const sessions = new Map(); const locks = new Map(); const cooldowns = new Map(); const SESSION_MS = 2 * 60 * 1000;
function lock(userId, task) { const previous = locks.get(userId) || Promise.resolve(); const current = previous.then(task, task); locks.set(userId, current); current.finally(() => { if (locks.get(userId) === current) locks.delete(userId); }).catch(() => {}); return current; }
function expire(id) { const session = sessions.get(id); if (session && Date.now() >= session.expiresAt) { session.state = 'EXPIRED'; sessions.delete(id); } }
function parseAmount(value) { const text = value.trim(); if (!/^[1-9][0-9]*$/.test(text)) return null; const amount = Number(text); return Number.isSafeInteger(amount) ? amount : null; }
function panel(session, balance) { return { embeds: [new EmbedBuilder().setColor(0xf4c95d).setTitle('🎰 PIKAPENG’S CASINO™').setDescription(`Your bet:\n🐟 **${session.betAmount} Fish**\n\nYour wallet:\n🐟 **${balance} Fish**\n\nIf you win:\n🐟 **2x payout**\nNet profit: **+${session.betAmount} Fish**\n\nIf you lose:\n🐟 **You lose your bet**\nNet loss: **-${session.betAmount} Fish**\n\n${config.pengEmoji()} “I have absolutely studied economics.”`)], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gamble_play:${session.id}`).setLabel('🎰 GAMBLE').setStyle(ButtonStyle.Danger), new ButtonBuilder().setCustomId(`gamble_cancel:${session.id}`).setLabel('❌ RUN AWAY').setStyle(ButtonStyle.Secondary))] }; }
async function open(i) { return i.showModal(new ModalBuilder().setCustomId('gamble_modal').setTitle("🎰 PikaPeng's Casino").addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('gamble_amount').setLabel('How many Fish do you want to bet?').setPlaceholder('Example: 100').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(20)))); }
async function submit(i) { return lock(i.user.id, async () => { const existing = [...sessions.values()].find((s) => s.userId === i.user.id && s.state === 'PENDING' && Date.now() < s.expiresAt); if (existing) return i.reply({ content: '🎰 You already have an active casino session. Finish it or run away first.', ephemeral: true }); const amount = parseAmount(i.fields.getTextInputValue('gamble_amount')); if (!amount) return i.reply({ content: '🐟 INVALID BET\n\nEnter a whole number of Fish greater than 0.\n\nNo Fish were changed.', ephemeral: true }); const balance = await economy.getFishBalance(i.user.id); if (amount > balance) return i.reply({ content: `🚫 NOT ENOUGH FISH\n\nYou tried to bet:\n🐟 **${amount}**\n\nYour wallet:\n🐟 **${balance}**`, ephemeral: true }); const session = { id: crypto.randomBytes(12).toString('hex'), userId: i.user.id, guildId: i.guildId, betAmount: amount, createdAt: Date.now(), expiresAt: Date.now() + SESSION_MS, state: 'PENDING' }; sessions.set(session.id, session); setTimeout(() => expire(session.id), SESSION_MS); return i.reply({ ...panel(session, balance), ephemeral: true }); }); }
async function play(i, id) { expire(id); const session = sessions.get(id); if (!session || session.state !== 'PENDING') return i.reply({ content: '⌛ CASINO SESSION EXPIRED\n\nPikaPeng closed the table.\n\nRun `/gamble` again.\n\nNo Fish were changed.', ephemeral: true }); if (session.userId !== i.user.id) return i.reply({ content: `${config.pengEmoji()} Hey! That casino session belongs to someone else.`, ephemeral: true }); return lock(session.userId, async () => { if (!sessions.has(id) || session.state !== 'PENDING') return i.reply({ content: '⌛ CASINO SESSION EXPIRED', ephemeral: true }); const current = await economy.getFishBalance(session.userId); if (current < session.betAmount) return i.update({ content: `🚫 BET NO LONGER VALID\n\nRequired: 🐟 **${session.betAmount}**\nAvailable: 🐟 **${current}**\n\nNo gamble occurred.\nNo Fish changed.`, embeds: [], components: [] }); session.state = 'PROCESSING'; const won = crypto.randomInt(0, 2) === 1; try { const result = await economy.resolveGamble(session.userId, session.betAmount, won); session.state = 'COMPLETED'; sessions.delete(id); cooldowns.set(session.userId, Date.now()); logger.info(`Gamble ${session.id}: ${session.userId} ${session.guildId} bet=${session.betAmount} ${won ? 'WIN' : 'LOSE'} reward=${won ? session.betAmount : 0} balance=${result.after}`); if (won) return i.update({ content: `🎰 JACKPOT!\n\nYou bet:\n🐟 **${session.betAmount} Fish**\n\nPayout:\n🐟 **${session.betAmount * 2} Fish**\n\nProfit:\n🐟 **+${session.betAmount} Fish**\n\nYour wallet:\n🐟 **${result.after} Fish**\n\n${config.pengEmoji()} PikaPeng actually paid out. Incredible.`, embeds: [], components: [] }); return i.update({ content: `💀 YOU LOST!\n\nYou bet:\n🐟 **${session.betAmount} Fish**\n\nFish lost:\n🐟 **${session.betAmount} Fish**\n\nYour wallet:\n🐟 **${result.after} Fish**\n\n${config.pengEmoji()} PikaPeng thanks you for your generous donation.`, embeds: [], components: [] }); } catch (error) { session.state = 'PENDING'; logger.error(`Gamble resolution failed for ${session.userId}`, error); return i.update({ content: `${config.pengEmoji()} PikaPeng dropped the casino paperwork.\n\nThe result couldn't be completed safely.\n\nPlease try again later.`, embeds: [], components: [] }); } }); }
function cancel(i, id) { const session = sessions.get(id); if (!session || session.userId !== i.user.id || session.state !== 'PENDING') return i.reply({ content: '⌛ CASINO SESSION EXPIRED', ephemeral: true }); session.state = 'CANCELLED'; sessions.delete(id); return i.update({ content: `🏃 YOU ESCAPED THE CASINO\n\nFish lost:\n🐟 **0**\n\nFish won:\n🐟 **0**\n\n${config.pengEmoji()} PikaPeng looks disappointed.`, embeds: [], components: [] }); }
async function checkCooldown(i) { const last = cooldowns.get(i.user.id) || 0; const next = last + (Number(process.env.GAMBLE_COOLDOWN_SECONDS) || 300) * 1000; if (Date.now() < next) return i.reply({ content: `⏳ PIKAPENG IS COUNTING FISH\n\nYou can gamble again <t:${Math.ceil(next / 1000)}:R>.\n\n${config.pengEmoji()} Even financially irresponsible penguins need cooldowns.`, ephemeral: true }); return null; }
module.exports = { data: new SlashCommandBuilder().setName('gamble').setDescription('Visit PikaPeng’s casino.'), open, submit, play, cancel, checkCooldown, execute: async (i) => { const blocked = await checkCooldown(i); return blocked || open(i); } };
