const crypto = require('node:crypto');
const { SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const economy = require('../economy');
const config = require('../config');
const logger = require('../utils/logger');
const pending = new Map(); const locks = new Map(); const TTL = 2 * 60 * 1000;
function lock(userId, task) { const previous = locks.get(userId) || Promise.resolve(); const current = previous.then(task, task); locks.set(userId, current); current.finally(() => { if (locks.get(userId) === current) locks.delete(userId); }).catch(() => {}); return current; }
function expire(id) { const item = pending.get(id); if (item && Date.now() >= item.expiresAt) { item.state = 'EXPIRED'; pending.delete(id); } }
function panel(item, balance) { return { embeds: [new EmbedBuilder().setColor(0x6bd6e8).setTitle(`${config.pengEmoji()} FISH TRANSFER`).setDescription(`From:\n<@${item.fromId}>\n\nTo:\n<@${item.toId}>\n\nAmount:\n🐟 **${item.amount} Fish**\n\nYour Wallet:\n🐟 **${balance} Fish**\n\nAfter Transfer:\n🐟 **${balance - item.amount} Fish**\n\nTransaction Fee:\n🐟 **0 Fish**`)], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`givefish_confirm:${item.id}`).setLabel('🐟 GIVE FISH').setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`givefish_cancel:${item.id}`).setLabel('❌ CANCEL').setStyle(ButtonStyle.Secondary))] }; }
async function begin(i, target, amount) { return lock(i.user.id, async () => { const balance = await economy.getFishBalance(i.user.id); const item = { id: crypto.randomBytes(12).toString('hex'), fromId: i.user.id, toId: target.id, amount, state: 'PENDING', expiresAt: Date.now() + TTL }; pending.set(item.id, item); setTimeout(() => expire(item.id), TTL); return { item, balance }; }); }
async function confirm(i, id) { expire(id); const item = pending.get(id); if (!item || item.state !== 'PENDING') return i.reply({ content: '⌛ This Fish transfer has expired.\n\nRun `/givefish` again if you still want to send them.', ephemeral: true }); if (i.user.id !== item.fromId) return i.reply({ content: `${config.pengEmoji()} This Fish transfer belongs to someone else.`, ephemeral: true }); return lock(item.fromId, async () => { if (!pending.has(id) || item.state !== 'PENDING') return i.reply({ content: '⌛ This Fish transfer has expired.', ephemeral: true }); item.state = 'PROCESSING'; const balance = await economy.getFishBalance(item.fromId); if (balance < item.amount) { item.state = 'CANCELLED'; pending.delete(id); return i.update({ content: `🚫 NOT ENOUGH FISH\n\nYour balance changed before the transfer was confirmed.\n\nRequired: 🐟 **${item.amount}**\nAvailable: 🐟 **${balance}**\n\nNo Fish were transferred.`, embeds: [], components: [] }); } try { const result = await economy.transferFish(item.fromId, item.toId, item.amount); item.state = 'COMPLETED'; pending.delete(id); const recipient = await i.client.users.fetch(item.toId).catch(() => null); if (recipient) recipient.send({ embeds: [new EmbedBuilder().setColor(0x6bd6e8).setTitle('🐟 YOU RECEIVED FISH!').setDescription(`<@${item.fromId}> gave you:\n\n🐟 **${item.amount} Fish**\n\nYour Wallet:\n🐟 **${result.recipientBalance} Fish**\n\n${config.pengEmoji()} PikaPeng Delivery Service`)] }).catch(() => {}); return i.update({ content: `✅ FISH DELIVERED!\n\n🐟 **${item.amount} Fish**\n\n<@${item.fromId}>\n⬇️\n<@${item.toId}>\n\nYour Wallet:\n🐟 **${result.senderBalance} Fish**\n\nTransaction Fee:\n🐟 **0 Fish**\n\n${config.pengEmoji()} PikaPeng has approved the transaction.`, embeds: [], components: [] }); } catch (error) { item.state = 'PENDING'; logger.error(`Fish transfer failed for ${item.fromId} to ${item.toId}`, error); return i.update({ content: `${config.pengEmoji()} PikaPeng dropped the Fish transfer paperwork.\n\nThe transfer couldn't be completed.\n\nNo successful transfer was recorded.\n\nPlease try again.`, embeds: [], components: [] }); } }); }
function cancel(i, id) { const item = pending.get(id); if (!item || item.fromId !== i.user.id || item.state !== 'PENDING') return i.reply({ content: '⌛ This Fish transfer has expired.', ephemeral: true }); item.state = 'CANCELLED'; pending.delete(id); return i.update({ content: `❌ TRANSFER CANCELLED\n\nFish transferred:\n🐟 **0**\n\nYour Fish remain safely inside the PikaPeng vault. ${config.pengEmoji()}`, embeds: [], components: [] }); }
module.exports = { data: new SlashCommandBuilder().setName('givefish').setDescription('Transfer Fish to another member.').addUserOption((o) => o.setName('user').setDescription('The member receiving Fish').setRequired(true)).addIntegerOption((o) => o.setName('amount').setDescription('A positive whole number of Fish').setRequired(true).setMinValue(1)), async execute(i) { const target = i.options.getUser('user'); const amount = i.options.getInteger('amount'); if (!Number.isInteger(amount) || amount < 1) return i.reply({ content: '🐟 That’s not a valid Fish amount.\n\nEnter a whole number greater than 0.', ephemeral: true }); if (target.id === i.user.id) return i.reply({ content: `${config.pengEmoji()} You cannot give Fish to yourself.\n\nPikaPeng has detected suspicious accounting.`, ephemeral: true }); if (target.bot) return i.reply({ content: '🤖 Bots don’t need Fish.\n\nPikaPeng already feeds the servers.', ephemeral: true }); const member = await i.guild.members.fetch(target.id).catch(() => null); if (!member) return i.reply({ content: '🐟 That user is not currently in this server.', ephemeral: true }); const balance = await economy.getFishBalance(i.user.id); if (balance < amount) return i.reply({ content: `🚫 NOT ENOUGH FISH\n\nYou're trying to give:\n🐟 **${amount}**\n\nYour wallet:\n🐟 **${balance}**\n\nPikaPeng cannot transfer Fish that do not exist.`, ephemeral: true }); const result = await begin(i, target, amount); return i.reply({ ...panel(result.item, result.balance), ephemeral: true }); } };
module.exports.confirm = confirm;
module.exports.cancel = cancel;
