const { SlashCommandBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder } = require('discord.js');
const uber = require('../pikauber');
const data = new SlashCommandBuilder().setName('pikauber').setDescription('Order fictional free food from PikaUber').addSubcommand(s=>s.setName('order').setDescription('Order food')).addSubcommand(s=>s.setName('status').setDescription('View your order')).addSubcommand(s=>s.setName('history').setDescription('View order history'));
function menuUi(user){return {content:'🍔 **PIKAUBER**\n\nWhat do you want delivered?\n\nEverything is 100% free.\n\nPrice: 🐟 0\nDelivery fee: 🐟 0\nService fee: 🐟 0\nTax: 🐟 0',components:[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`uber_food:${user}`).setPlaceholder('CHOOSE FOOD').addOptions(uber.menu().map(x=>({label:x.name,value:x.id,emoji:x.emoji})))),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`uber_history:${user}`).setLabel('ORDER HISTORY').setStyle(ButtonStyle.Secondary))]};}
function display(o){return `🍔 **PIKAUBER STATUS**\n\nOrder: ${o.orderId}\n\n${o.emoji} ${o.foodName}\n\nDriver: 🐧 PikaPeng\nVehicle: ${o.vehicle}\nStatus: ${o.status}\nTOTAL: 🐟 0`;}
async function execute(i){const s=i.options.getSubcommand();if(s==='history'){const h=await uber.history(i.user.id);return i.reply({content:h.map(o=>`${o.orderId}\n${o.emoji} ${o.foodName}\n${o.status}\n🐟 0`).join('\n\n')||'No PikaUber orders yet.',ephemeral:true});}if(s==='status'){const o=await uber.latest(i.user.id);return i.reply({content:o?display(o):'No PikaUber order yet.',ephemeral:true});}return i.reply({...menuUi(i.user.id),ephemeral:true});}
async function select(i){const user=i.customId.split(':')[1];if(user!==i.user.id)return i.reply({content:'This PikaUber menu belongs to another user.',ephemeral:true});await i.deferUpdate();const r=await uber.create(i.user.id,i.values[0]);if(r.error==='active')return i.editReply({content:`🚗 PikaPeng is already delivering your food.\n\n${r.order.emoji} ${r.order.foodName}\nETA: ${Math.max(0,Math.ceil((r.order.expectedDeliveryAt-Date.now())/1000))} seconds`,components:[]});if(r.error)return i.editReply({content:'That food is unavailable.',components:[]});return i.editReply({content:`${r.order.emoji} **ORDER CONFIRMED**\n\nOrder: ${r.order.orderId}\n1× ${r.order.foodName}\n\nTOTAL: 🐟 0\n\nFinding a delivery penguin...\n\n${display(r.order)}`,components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`uber_cancel:${r.order.orderId}`).setLabel('CANCEL').setStyle(ButtonStyle.Danger))]});}
async function button(i){const [a,id]=i.customId.split(':');if(a==='uber_history'){if(id!==i.user.id)return i.reply({content:'This PikaUber menu belongs to another user.',ephemeral:true});await i.deferUpdate();const h=await uber.history(i.user.id);return i.editReply({content:h.map(o=>`${o.orderId} — ${o.emoji} ${o.foodName} — ${o.status}`).join('\n')||'No orders.',components:[]});}const o=await uber.status(id,i.user.id);if(!o)return i.reply({content:'This order is not yours or no longer exists.',ephemeral:true});await i.deferUpdate();if(a==='uber_cancel'){const r=await uber.cancel(id,i.user.id);return i.editReply({content:r.error==='late'?'❌ Too late to cancel. PikaPeng is already coming.':'PikaUber order cancelled.',components:[]});}const r=await uber.eat(id,i.user.id);return i.editReply({content:r.error?'🍔 The food has not arrived yet.':'🍕 You ate the food.\n\nHunger restored: absolutely nothing.\n\n🐧 PikaPeng hopes you enjoyed it.',components:[]});}
module.exports={data,execute,select,button,menuUi};
