const crypto=require('node:crypto');
const {SlashCommandBuilder,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');
const {claimWaddle,getWaddleStats,dateKey,timezone}=require('../waddle'); const config=require('../config'); const views=new Map();
function month(){const p=new Intl.DateTimeFormat('en-US',{timeZone:timezone,year:'numeric',month:'2-digit'}).formatToParts(new Date());return `${p.find(x=>x.type==='year').value}-${p.find(x=>x.type==='month').value}`;}
function shift(k,n){const [y,m]=k.split('-').map(Number),d=new Date(Date.UTC(y,m-1+n,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
function embed(u,s,k){const [y,m]=k.split('-').map(Number),first=new Date(Date.UTC(y,m-1,1)),count=new Date(Date.UTC(y,m,0)).getUTCDate(),offset=(first.getUTCDay()+6)%7,today=dateKey(),set=new Set(s.history),cells=['Mo','Tu','We','Th','Fr','Sa','Su'];for(let i=0;i<offset;i++)cells.push('  ');for(let d=1;d<=count;d++){const key=`${k}-${String(d).padStart(2,'0')}`;cells.push(key>today?'⬜':set.has(key)?'🟩':'⬛');}while(cells.length%7)cells.push('  ');const rows=[];for(let i=0;i<cells.length;i+=7)rows.push(cells.slice(i,i+7).join(' '));return new EmbedBuilder().setColor(0x6bd6e8).setTitle(`${config.pengEmoji()} ${u.displayName}'s Waddle Calendar`).setDescription(`**${first.toLocaleString('en-US',{month:'long',timeZone:'UTC'})} ${y}**\n\n${rows.join('\n')}\n\n🟩 Waddled　⭐ Milestone waddle\n⬛ Known missed day　⬜ Future`).addFields({name:'Waddle stats',value:`🔥 Current streak: **${s.currentStreak} days**\n🏆 Longest streak: **${s.longestStreak} days**\n${config.pengEmoji()} Total waddles: **${s.totalWaddles}**`});}
function row(id,k){const now=month();return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`waddle_calendar:${id}:${shift(k,-1)}`).setLabel('◀ Previous').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`waddle_calendar:${id}:${now}`).setLabel('📅 Current').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`waddle_calendar:${id}:${shift(k,1)}`).setLabel('Next ▶').setStyle(ButtonStyle.Secondary).setDisabled(k>=now))];}
async function calendar(i,k){const u=i.options.getUser('user')||i.user,s=await getWaddleStats(u.id),id=crypto.randomBytes(8).toString('hex');views.set(id,{owner:i.user.id,target:u.id,expires:Date.now()+900000});setTimeout(()=>views.delete(id),900000);return i.reply({embeds:[embed(u,s,k)],components:row(id,k),ephemeral:true});}
async function handleButton(i){if(!i.customId.startsWith('waddle_calendar:'))return false;const[,id,k]=i.customId.split(':'),v=views.get(id);if(!v||v.owner!==i.user.id||Date.now()>v.expires)return i.reply({content:`${config.pengEmoji()} This calendar has expired.`,ephemeral:true});const u=await i.client.users.fetch(v.target),s=await getWaddleStats(v.target);return i.update({embeds:[embed(u,s,k)],components:row(id,k)});}
module.exports={data:new SlashCommandBuilder().setName('waddle').setDescription('Check in or view your Waddle Calendar.').addSubcommand(s=>s.setName('calendar').setDescription('View waddled days by month.').addStringOption(o=>o.setName('month').setDescription('Month').addChoices({name:'Previous',value:'previous'},{name:'Current',value:'current'})).addUserOption(o=>o.setName('user').setDescription('Member calendar to view'))),handleButton,async execute(i){if(i.options.getSubcommand(false)==='calendar')return calendar(i,i.options.getString('month')==='previous'?shift(month(),-1):month());if(i.user.bot)return i.reply({content:`${config.pengEmoji()} Bots cannot waddle.`,ephemeral:true});const r=await claimWaddle(i.user.id);if(r.alreadyClaimed)return i.reply({content:`${config.pengEmoji()} You've already waddled today!\n\n🔥 Current streak: ${r.stats.currentStreak} days\nCome back tomorrow!`,ephemeral:true});return i.reply({content:`${config.pengEmoji()} Waddle!\nYou waddled into the Igloo today.\n\n🐟 +${r.reward} Fish\n🔥 Streak: ${r.stats.currentStreak} days\n${config.pengEmoji()} Total waddles: ${r.stats.totalWaddles}\n🏆 Longest streak: ${r.stats.longestStreak} days`});}};
