const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const config = require('../config');
async function handleModal(i) {
  if (i.customId === 'gamble_modal') { const gamble = require('../commands/gamble'); return gamble.submit(i); }
  if (i.customId.startsWith('ktv_rename_modal:') || i.customId.startsWith('ktv_limit_modal:')) { const [kind, channelId] = i.customId.split(':'); const manage = require('../commands/ktvmanage'); const ktv = require('../ktv-manager'); const room = await manage.owned(i, channelId); if (!room) return i.reply({ content: '🏚️ This KTV rental is no longer active.', ephemeral: true }); if (kind === 'ktv_rename_modal') { const custom = i.fields.getTextInputValue('ktv_name').trim(); if (!custom) return i.reply({ content: '🐧 Please enter a name.', ephemeral: true }); await room.channel.setName(`${custom}'s PikaPeng Rented KTV`.slice(0, 100)); } else { const limit = Number(i.fields.getTextInputValue('ktv_limit').trim()); if (!Number.isInteger(limit) || limit < 0 || limit > 99) return i.reply({ content: '🐧 Enter a whole number from 0 to 99.', ephemeral: true }); await room.channel.setUserLimit(limit); } return i.reply({ ...manage.panel(await ktv.getOwnedRoom(i.guild, i.user.id)), ephemeral: true }); }
  if (i.customId === 'global_cooldown_modal') { const command = require('../commands/global-cooldown'); if (!command.canManage(i)) return i.reply({ content: '🐧 You no longer have permission to change the global cooldown.', ephemeral: true }); const seconds = Number(i.fields.getTextInputValue('cooldown_seconds').trim()); if (!Number.isInteger(seconds) || seconds < 0 || seconds > 21600) return i.reply({ content: '🐧 Enter a whole number from 0 to 21600.', ephemeral: true }); return command.applyCooldown(i, seconds); }
  if (i.customId !== 'announcement_modal') return false;
  const title = i.fields.getTextInputValue('announcement_title'); const content = i.fields.getTextInputValue('announcement_content'); const link = i.fields.getTextInputValue('announcement_link'); const footer = i.fields.getTextInputValue('announcement_footer');
  const safe = (value) => config.allowAnnouncementMentions() ? value : value.replace(/@(everyone|here|&?\d+|!?\d+)/gi, '@​$1');
  const embed = new EmbedBuilder().setColor(0x6bd6e8).setTitle(title).setDescription(safe(content)).setAuthor({ name: `${i.user.username} via PengBot <:PikaPeng:1551171560432345138> :` }).setTimestamp(); if (link) embed.setURL(link); if (footer) embed.setFooter({ text: footer });
  return i.reply({ content: 'Private preview — publish when ready:', embeds: [embed], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('announcement_publish').setLabel('Publish').setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId('announcement_cancel').setLabel('Cancel').setStyle(ButtonStyle.Secondary))], ephemeral: true });
}
module.exports = { handleModal };
