const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const logger = require('./utils/logger');
const storePath = path.join(__dirname, 'data', 'ad-submissions.json');
const REVIEW_CHANNEL_ID = '1551168500964270091';
const ADS_CHANNEL_ID = '1552674588373164213';
const VERIFIERS = new Set(['1547892939362013224', '1290053141361852446']);
let records = {}; let loaded = false; const locks = new Map();
async function load() { if (loaded) return; try { records = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { records = {}; } loaded = true; }
async function save() { await fs.writeFile(storePath, `${JSON.stringify(records, null, 2)}\n`, 'utf8'); }
function lock(id, task) { const p = (locks.get(id) || Promise.resolve()).then(task, task); locks.set(id, p); p.finally(() => locks.get(id) === p && locks.delete(id)).catch(() => {}); return p; }
function safe(value) { return String(value).replace(/@(everyone|here|&?\d+|!?\d+)/gi, '@﹫'); }
function validUrl(value) { if (!value) return null; try { const url = new URL(value); return ['http:', 'https:'].includes(url.protocol) ? url.toString() : null; } catch { return null; } }
function reviewComponents(id, disabled = false) { return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`ad_approve:${id}`).setLabel('✅ Approve').setStyle(ButtonStyle.Success).setDisabled(disabled), new ButtonBuilder().setCustomId(`ad_reject:${id}`).setLabel('❌ Reject').setStyle(ButtonStyle.Danger).setDisabled(disabled))]; }
function reviewEmbed(ad) { const embed = new EmbedBuilder().setColor(0xf4c95d).setTitle('Advertisement Review').addFields({ name: 'Advertiser', value: `${safe(ad.username)}\nDiscord ID: \`${ad.userId}\`` }, { name: 'Title', value: safe(ad.title) }, { name: 'Description', value: safe(ad.description) }); if (ad.url) embed.addFields({ name: 'URL', value: safe(ad.url) }); if (ad.imageUrl) embed.setImage(ad.imageUrl); return embed.setTimestamp(new Date(ad.createdAt)).setFooter({ text: `Submission ID: ${ad.id}` }); }
async function submit(client, data) { await load(); const id = crypto.randomBytes(12).toString('hex'); const ad = { ...data, id, status: 'PENDING', createdAt: new Date().toISOString(), reviewChannelId: REVIEW_CHANNEL_ID }; const channel = await client.channels.fetch(REVIEW_CHANNEL_ID).catch(() => null); if (!channel?.isTextBased()) throw new Error('Review channel unavailable'); const message = await channel.send({ embeds: [reviewEmbed(ad)], components: reviewComponents(id), allowedMentions: { parse: [] } }); ad.reviewMessageId = message.id; records[id] = ad; await save(); return ad; }
async function process(interaction, id, approve) { await load(); if (!VERIFIERS.has(interaction.user.id)) return interaction.reply({ content: '🐧 Only the Ad Verification Team can review advertisements.', ephemeral: true }); return lock(id, async () => { const ad = records[id]; if (!ad || ad.status !== 'PENDING') return interaction.reply({ content: 'This advertisement has already been processed or is unavailable.', ephemeral: true }); if (approve) { const channel = await interaction.client.channels.fetch(ADS_CHANNEL_ID).catch(() => null); if (!channel?.isTextBased()) return interaction.reply({ content: 'The advertisements channel is unavailable.', ephemeral: true }); const publicEmbed = new EmbedBuilder().setColor(0x6bd6e8).setTitle(`📢 Sponsored · ${safe(ad.title)}`).setDescription(safe(ad.description)).setFooter({ text: 'PikaStudio Advertisements' }).setTimestamp(); if (ad.url) publicEmbed.setURL(ad.url).addFields({ name: 'Link', value: safe(ad.url) }); if (ad.imageUrl) publicEmbed.setImage(ad.imageUrl); await channel.send({ embeds: [publicEmbed], allowedMentions: { parse: [] } }); ad.status = 'APPROVED'; ad.processedBy = interaction.user.id; ad.processedAt = new Date().toISOString(); await save(); await interaction.update({ embeds: [reviewEmbed(ad).setColor(0x57f287).addFields({ name: 'Decision', value: `✅ Approved by <@${interaction.user.id}>` })], components: reviewComponents(id, true) }); logger.info(`Advertisement ${id} approved by ${interaction.user.id}`); return; } ad.status = 'REJECTED'; ad.processedBy = interaction.user.id; ad.processedAt = new Date().toISOString(); await save(); await interaction.update({ embeds: [reviewEmbed(ad).setColor(0xed4245).addFields({ name: 'Decision', value: `❌ Rejected by <@${interaction.user.id}>` })], components: reviewComponents(id, true) }); logger.info(`Advertisement ${id} rejected by ${interaction.user.id}`); }); }
module.exports = { submit, process, validUrl };
