const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const economy = require('./economy');
const config = require('./config');
const logger = require('./utils/logger');
const { discordTimestamp } = require('./utils/time');
const storePath = path.join(__dirname, 'data', 'bank-investments.json');
const BANK_DURATION_MS = config.bankDurationMs(); const BANK_INTEREST_RATE = config.bankInterestRate(); const BANK_COMPOUND_PERIODS = config.bankCompoundPeriods(); const BANK_MAX_DEPOSIT = config.bankMaxDeposit();
let records = {}; let loaded = false; let queue = Promise.resolve(); const timers = new Map();
const mutate = (task) => { const next = queue.then(task, task); queue = next.catch(() => {}); return next; };
async function load() { if (loaded) return; try { records = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { records = {}; } loaded = true; }
async function save() { await fs.writeFile(storePath, `${JSON.stringify(records, null, 2)}\n`, 'utf8'); }
function utcDay(ms) { return new Date(ms).toISOString().slice(0, 10); }
function nextMidnight(ms) { const d = new Date(ms); return Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate() + 1); }
function calculatePayout(principal) { const payout = Math.floor(principal * Math.pow(1 + BANK_INTEREST_RATE, BANK_COMPOUND_PERIODS)); if (!Number.isSafeInteger(payout)) throw new RangeError('The expected payout exceeds the safe Fish limit.'); return payout; }
function activeFor(userId) { return Object.values(records).find((r) => r.userId === userId && r.status === 'active'); }
function schedule(id, client) { if (timers.has(id)) clearTimeout(timers.get(id)); const r = records[id]; if (!r || r.status !== 'active') return; timers.set(id, setTimeout(() => resolve(id, client).catch((e) => logger.error('Bank payout failed', e)), Math.max(0, r.payoutAt - Date.now()))); }
async function resolve(id, client) { return mutate(async () => { await load(); const r = records[id]; if (!r || r.status !== 'active' || Date.now() < r.payoutAt) return { already: true, record: r }; const payoutAmount = calculatePayout(r.principal); const interestEarned = payoutAmount - r.principal; const balance = await economy.addFish(r.userId, payoutAmount); r.status = 'paid'; r.paidAt = Date.now(); r.payoutAmount = payoutAmount; r.interestEarned = interestEarned; await save(); timers.delete(id); logger.info(`[BANK_PAYOUT] investment=${id} user=${r.userId} principal=${r.principal} payout=${payoutAmount} bankDayUtc=${r.bankDayUtc} timestamp=${new Date(r.paidAt).toISOString()}`); const user = await client.users.fetch(r.userId).catch(() => null); const availability = utcDay(Date.now()) === r.bankDayUtc ? `\n\n🐧 IglooBank is closed for you for the rest of today.\nAvailable again: ${discordTimestamp(nextMidnight(Date.now()))}` : '\n\n🐧 A new UTC day has started — you may bank again.'; await user?.send(`🏦 IGLOOBANK PAYOUT\n\nYour investment has matured!\n\nOriginal deposit: ${r.principal.toLocaleString()} 🐟\nInterest earned: +${interestEarned.toLocaleString()} 🐟\n────────────────\n💰 Returned: ${payoutAmount.toLocaleString()} 🐟\n\nThe fish have been returned to your wallet.${availability}`).catch(() => logger.info(`[BANK_PAYOUT_DM_FAILED] investment=${id} user=${r.userId}`)); return { already: false, record: r, balance }; }); }
async function start(client, userId, amount, theft) { return mutate(async () => { await load(); const day = utcDay(Date.now()); const existing = activeFor(userId); if (existing) return { error: 'active', investment: existing }; if (Object.values(records).some((r) => r.userId === userId && r.bankDayUtc === day)) return { error: 'daily' }; if (await theft.hasActiveTheftAsThief(userId)) return { error: 'theft' }; if (!Number.isSafeInteger(amount) || amount < 1 || amount > BANK_MAX_DEPOSIT) return { error: 'amount' }; const balance = await economy.getFishBalance(userId); if (amount > balance) return { error: 'funds' }; const payout = calculatePayout(amount); const now = Date.now(); const investment = { id: crypto.randomUUID(), userId, principal: amount, startedAt: now, payoutAt: now + BANK_DURATION_MS, bankDayUtc: day, status: 'active' }; await economy.removeFish(userId, amount); try { records[investment.id] = investment; await save(); } catch (error) { delete records[investment.id]; await economy.addFish(userId, amount); throw error; } schedule(investment.id, client); logger.info(`[BANK_DEPOSIT] investment=${investment.id} user=${userId} principal=${amount} payout=${payout} bankDayUtc=${day} timestamp=${new Date(now).toISOString()}`); return { investment, payout, profit: payout - amount }; }); }
async function restore(client) { await load(); for (const r of Object.values(records)) if (r.status === 'active') { if (Date.now() >= r.payoutAt) await resolve(r.id, client); else schedule(r.id, client); logger.info(`[BANK_RESTORE] investment=${r.id} user=${r.userId} payoutAt=${new Date(r.payoutAt).toISOString()}`); } }
module.exports = { start, resolve, restore, calculatePayout, utcDay, nextMidnight, BANK_DURATION_MS, BANK_INTEREST_RATE, BANK_COMPOUND_PERIODS, BANK_MAX_DEPOSIT };
