const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const logger = require('./utils/logger');
const config = require('./config');
const storePath = path.join(__dirname, 'data', 'boop-stats.json');
let state = {}; let loaded = false; const locks = new Map(); const cooldowns = new Map(); const COOLDOWN = 5000;
async function load() { if (loaded) return; try { state = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { state = { counts: {}, boops: {} }; } state.counts ||= {}; state.boops ||= {}; loaded = true; }
async function save() { await fs.writeFile(storePath, `${JSON.stringify(state, null, 2)}\n`, 'utf8'); }
function lock(id, task) { const p = (locks.get(id) || Promise.resolve()).then(task, task); locks.set(id, p); p.finally(() => locks.get(id) === p && locks.delete(id)).catch(() => {}); return p; }
function canBoop(userId) { const next = cooldowns.get(userId) || 0; if (Date.now() < next) return false; cooldowns.set(userId, Date.now() + COOLDOWN); return true; }
function count(userId) { return state.counts[userId] || 0; }
function components(token) { return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`boop_back:${token}`).setLabel(`${config.pengEmoji()} BOOP BACK`).setStyle(ButtonStyle.Primary))]; }
function embed(sender, recipient, total) { return new EmbedBuilder().setColor(0x6bd6e8).setTitle(`${config.pengEmoji()} You've been booped!`).setDescription(`**${sender.username}** booped you.\n\nYou've been booped **${total} times**.`).setFooter({ text: 'PengBot · PikaStudio' }); }
async function deliver(client, senderId, targetId) { await load(); if (senderId === targetId) return { self: true }; if (!canBoop(senderId)) return { limited: true }; const target = await client.users.fetch(targetId); if (!target || target.bot) return { bot: true }; const token = crypto.randomBytes(16).toString('hex'); const record = { senderId, recipientId: targetId, createdAt: new Date().toISOString(), used: false }; state.boops[token] = record; const sender = await client.users.fetch(senderId); const total = count(targetId) + 1; try { await target.send({ embeds: [embed(sender, target, total)], components: components(token) }); } catch (error) { delete state.boops[token]; logger.error(`Boop DM failed for ${targetId}`, error); return { dmFailed: true }; } return lock(targetId, async () => { state.counts[targetId] = total; await save(); return { delivered: true, total }; }); }
async function boopBack(interaction, token) { await load(); const record = state.boops[token]; if (!record || record.used) return interaction.reply({ content: '🐧 That boop has already been used or expired.', ephemeral: true }); if (interaction.user.id !== record.recipientId) return interaction.reply({ content: '🐧 That BOOP BACK button is not yours.', ephemeral: true }); if (record.senderId === interaction.user.id) return interaction.reply({ content: '🐧 You cannot boop yourself.', ephemeral: true }); if (!canBoop(interaction.user.id)) return interaction.reply({ content: '🐧 Easy on the boops! Try again in a moment.', ephemeral: true }); const target = await interaction.client.users.fetch(record.senderId).catch(() => null); if (!target || target.bot) return interaction.reply({ content: '🐧 The original booper is no longer available.', ephemeral: true }); const nextToken = crypto.randomBytes(16).toString('hex'); state.boops[token].used = true; state.boops[nextToken] = { senderId: interaction.user.id, recipientId: record.senderId, createdAt: new Date().toISOString(), used: false }; const total = count(record.senderId) + 1; try { await target.send({ embeds: [embed(interaction.user, target, total)], components: components(nextToken) }); state.counts[record.senderId] = total; await save(); return interaction.update({ content: '🐧 Boop back delivered!', embeds: [], components: [] }); } catch (error) { state.boops[token].used = false; delete state.boops[nextToken]; logger.error(`Boop-back DM failed for ${record.senderId}`, error); return interaction.reply({ content: '🐧 I could not deliver the boop back because I cannot DM them.', ephemeral: true }); } }
module.exports = { deliver, boopBack };
