const fs = require('node:fs/promises'); const path = require('node:path'); const config = require('./config');
const storePath = path.join(__dirname, 'data', 'chairs.json'); let records = {}; let loaded = false; let queue = Promise.resolve();
const mutate = task => { const next = queue.then(task, task); queue = next.catch(() => {}); return next; };
async function load() { if (loaded) return; try { records = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { records = {}; } loaded = true; } async function save() { await fs.writeFile(storePath, `${JSON.stringify(records, null, 2)}\n`, 'utf8'); }
function state(guildId) { return records[guildId] ||= { guildId, occupantUserId: null, satAtMs: null, chairCreatedAtMs: Date.now(), totalCompletedSits: 0, totalCompletedSitMs: 0, longestSitMs: 0, longestSitterUserId: null, shortestSitMs: null, shortestSitterUserId: null, userStats: {}, history: [] }; }
function duration(ms) { let seconds = Math.max(0, Math.floor(ms / 1000)); const days = Math.floor(seconds / 86400); seconds %= 86400; const hours = Math.floor(seconds / 3600); seconds %= 3600; const minutes = Math.floor(seconds / 60); seconds %= 60; return [days ? `${days}d` : '', hours ? `${hours}h` : '', minutes ? `${minutes}m` : '', seconds || (!days && !hours && !minutes) ? `${seconds}s` : ''].filter(Boolean).join(' '); }
async function view(guildId) { await load(); const c = state(guildId); return { ...c, durationMs: c.satAtMs ? Date.now() - c.satAtMs : 0 }; }
async function sit(guildId, userId) { return mutate(async () => { await load(); const c = state(guildId); if (c.occupantUserId) return { error: c.occupantUserId === userId ? 'self' : 'occupied', chair: c }; c.occupantUserId = userId; c.satAtMs = Date.now(); await save(); return { chair: c }; }); }
async function leave(guildId, userId) { return mutate(async () => { await load(); const c = state(guildId); if (c.occupantUserId !== userId) return { error: 'not-occupant' }; const satAtMs = c.satAtMs; const leftAtMs = Date.now(); const durationMs = Math.max(0, leftAtMs - satAtMs); const entry = { userId, satAtMs, leftAtMs, durationMs }; c.history.push(entry); c.history = c.history.slice(-config.chairHistoryLimit()); c.totalCompletedSits += 1; c.totalCompletedSitMs += durationMs; c.longestSitMs = Math.max(c.longestSitMs, durationMs); if (durationMs >= c.longestSitMs) c.longestSitterUserId = userId; if (c.shortestSitMs === null || durationMs < c.shortestSitMs) { c.shortestSitMs = durationMs; c.shortestSitterUserId = userId; } const stats = c.userStats[userId] ||= { completedSits: 0, totalSitMs: 0 }; stats.completedSits += 1; stats.totalSitMs += durationMs; c.occupantUserId = null; c.satAtMs = null; await save(); return { entry, chair: c }; }); }
async function stats(guildId) { await load(); const c = state(guildId); const most = Object.entries(c.userStats).sort((a, b) => b[1].completedSits - a[1].completedSits)[0]; return { ...c, durationMs: c.satAtMs ? Date.now() - c.satAtMs : 0, mostSitterUserId: most?.[0] || null, mostSits: most?.[1].completedSits || 0 }; }
async function history(guildId) { await load(); return [...state(guildId).history].reverse(); }
module.exports = { view, sit, leave, stats, history, duration };
