const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const sharp = require('sharp');
const economy = require('./economy');
const config = require('./config');
const logger = require('./utils/logger');

const GOAL = 100000;
const SIZE = 1000;
const TILE = 10;
const TILES = SIZE / TILE;
const statePath = path.join(__dirname, 'data', 'community-image.json');
const cacheRoot = path.join(__dirname, 'data', 'community-image-cache');
const assetsRoot = path.join(__dirname, 'assets', 'community');
let state = { active: null, lastImage: null };
let loaded = false;
let queue = Promise.resolve();
const validImage = /\.(png|jpe?g|webp)$/i;

function mutate(task) { const next = queue.then(async () => { await load(); return task(); }); queue = next.catch(() => {}); return next; }
async function load() { if (loaded) return; try { state = JSON.parse(await fs.readFile(statePath, 'utf8')); } catch { state = { active: null, lastImage: null }; } state ||= { active: null, lastImage: null }; loaded = true; }
async function save() { await fs.mkdir(path.dirname(statePath), { recursive: true }); const temp = `${statePath}.tmp`; await fs.writeFile(temp, `${JSON.stringify(state, null, 2)}\n`); await fs.rename(temp, statePath); }
function seedRandom(seed) { let x = crypto.createHash('sha256').update(seed).digest().readUInt32LE(0); return () => { x += 0x6D2B79F5; let t = x; t = Math.imul(t ^ t >>> 15, t | 1); t ^= t + Math.imul(t ^ t >>> 7, t | 61); return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
function shuffle(items, seed) { const random = seedRandom(seed); for (let i = items.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [items[i], items[j]] = [items[j], items[i]]; } return items; }
async function imageFiles() { return (await fs.readdir(assetsRoot, { withFileTypes: true }).catch(() => [])).filter(e => e.isFile() && validImage.test(e.name)).map(e => e.name); }
async function normalize(file) { const buffer = await sharp(path.join(assetsRoot, file)).resize(SIZE, SIZE, { fit: 'contain', background: { r: 255, g: 255, b: 255, alpha: 0 } }).ensureAlpha().raw().toBuffer({ resolveWithObject: true }); removeEdgeBackground(buffer.data); return buffer; }
function removeEdgeBackground(data) { const seen = new Uint8Array(SIZE * SIZE); const stack = []; for (let x = 0; x < SIZE; x++) stack.push([x, 0], [x, SIZE - 1]); for (let y = 1; y < SIZE - 1; y++) stack.push([0, y], [SIZE - 1, y]); while (stack.length) { const [x, y] = stack.pop(); const index = y * SIZE + x; if (seen[index]) continue; seen[index] = 1; const p = index * 4; if (data[p + 3] === 0) continue; const neighbours = [[x - 1, y], [x + 1, y], [x, y - 1], [x, y + 1]]; const edge = x === 0 || y === 0 || x === SIZE - 1 || y === SIZE - 1; if (!edge && !neighbours.some(([nx, ny]) => { if (nx < 0 || ny < 0 || nx >= SIZE || ny >= SIZE) return false; const q = (ny * SIZE + nx) * 4; return data[q + 3] === 0; })) continue; const similar = neighbours.some(([nx, ny]) => { if (nx < 0 || ny < 0 || nx >= SIZE || ny >= SIZE) return false; const q = (ny * SIZE + nx) * 4; return data[q + 3] > 0 && Math.abs(data[p] - data[q]) + Math.abs(data[p + 1] - data[q + 1]) + Math.abs(data[p + 2] - data[q + 2]) <= 18; }); if (edge || similar) { data[p + 3] = 0; for (const neighbour of neighbours) if (neighbour[0] >= 0 && neighbour[1] >= 0 && neighbour[0] < SIZE && neighbour[1] < SIZE) stack.push(neighbour); } } }
function revealableTiles(raw) { const { data } = raw; const tiles = []; for (let ty = 0; ty < TILES; ty++) for (let tx = 0; tx < TILES; tx++) { let meaningful = false; for (let y = ty * TILE; y < (ty + 1) * TILE && !meaningful; y++) for (let x = tx * TILE; x < (tx + 1) * TILE; x++) { const a = data[(y * SIZE + x) * 4 + 3]; if (a > 0) { meaningful = true; break; } } if (meaningful) tiles.push(ty * TILES + tx); } return tiles; }
async function ensureProject() { await load(); if (state.active) return state.active; const files = await imageFiles(); if (!files.length) throw new Error('No community images are installed yet.'); const choices = files.filter(file => files.length === 1 || file !== state.lastImage); const file = choices[Math.floor(Math.random() * choices.length)]; const raw = await normalize(file); const tiles = shuffle(revealableTiles(raw), `${file}:${Date.now()}:${crypto.randomBytes(16).toString('hex')}`); const id = crypto.randomUUID(); const cacheDir = path.join(cacheRoot, id); await fs.mkdir(cacheDir, { recursive: true }); await sharp(raw.data, { raw: { width: SIZE, height: SIZE, channels: 4 } }).png().toFile(path.join(cacheDir, 'full.png')); state.active = { id, image: file, fish: 0, goal: GOAL, revealOrder: tiles, cacheDir: path.relative(path.join(__dirname, 'data'), cacheDir), completed: false, pendingAnnouncement: false }; await save(); return state.active; }
async function rendered(project) { const raw = await sharp(path.join(__dirname, 'data', project.cacheDir, 'full.png')).raw().toBuffer({ resolveWithObject: true }); const count = Math.floor((project.fish / project.goal) * project.revealOrder.length); const revealed = new Set(project.revealOrder.slice(0, count)); for (let ty = 0; ty < TILES; ty++) for (let tx = 0; tx < TILES; tx++) if (!revealed.has(ty * TILES + tx)) for (let y = ty * TILE; y < (ty + 1) * TILE; y++) for (let x = tx * TILE; x < (tx + 1) * TILE; x++) raw.data[(y * SIZE + x) * 4 + 3] = 0; return sharp(raw.data, { raw: { width: SIZE, height: SIZE, channels: 4 } }).png().toBuffer(); }
async function progress() { return mutate(async () => { const project = await ensureProject(); return { fish: project.fish, goal: project.goal, percent: (project.fish / project.goal) * 100, image: await rendered(project), completed: project.completed, pendingAnnouncement: project.pendingAnnouncement }; }); }
async function contribute(userId, amount) { if (!Number.isSafeInteger(amount) || amount < 1) throw new RangeError('Contribution must be a positive whole number of Fish.'); return mutate(async () => { const project = await ensureProject(); if (project.completed || project.pendingAnnouncement) throw new Error('The community image is awaiting its completion announcement.'); const remaining = project.goal - project.fish; const contribution = Math.min(amount, remaining); if (contribution !== amount) throw new RangeError(`Only ${remaining.toLocaleString()} Fish are needed to finish this image.`); await economy.removeFish(userId, contribution); try { project.fish += contribution; if (project.fish === project.goal) { project.completed = true; project.pendingAnnouncement = true; } await save(); } catch (error) { await economy.addFish(userId, contribution).catch(() => {}); throw error; } return { contribution, fish: project.fish, goal: project.goal, completed: project.completed }; }); }
async function announcementPayload() { await load(); const project = state.active; if (!project?.pendingAnnouncement) return null; return { project, image: await fs.readFile(path.join(__dirname, 'data', project.cacheDir, 'full.png')) }; }
async function completeAfterAnnouncement() { return mutate(async () => { const project = state.active; if (!project?.pendingAnnouncement) return; state.lastImage = project.image; state.active = null; await save(); }); }
async function announce(client) { const payload = await announcementPayload(); if (!payload) return false; const channel = await client.channels.fetch(config.announcementsChannelId()); if (!channel?.isTextBased()) throw new Error('Configured announcements channel is unavailable.'); await channel.send({ content: '# :PikaPeng: COMMUNITY IMAGE COMPLETED! 🎉\n\n@everyone\n\nThe community did it!\n\n🐟 100,000 Fish were contributed to reveal the mystery image.', files: [{ attachment: payload.image, name: 'community-image.png' }], allowedMentions: { parse: ['everyone'] } }); await completeAfterAnnouncement(); logger.info('Community Image completion announcement sent.'); return true; }
async function retryAnnouncement(client) { try { await announce(client); } catch (error) { logger.error('Community Image announcement retry failed', error); } }
module.exports = { GOAL, progress, contribute, announce, retryAnnouncement };
