const fs = require('node:fs/promises'); const path = require('node:path'); const crypto = require('node:crypto'); const economy = require('./economy'); const logger = require('./utils/logger');
const storePath = path.join(__dirname, 'data', 'companies.json'); const SALARY = 100; const LEVEL_RANGES = { 1: [1, 3], 2: [2, 5], 3: [4, 8], 4: [6, 12], 5: [10, 20] }; let records = {}; let loaded = false; let saveQueue = Promise.resolve(); const locks = new Map();
function lock(id, task) { const p = locks.get(id) || Promise.resolve(); const c = p.then(task, task); locks.set(id, c); c.finally(() => { if (locks.get(id) === c) locks.delete(id); }).catch(() => {}); return c; }
async function load() { if (loaded) return; try { records = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { records = {}; } loaded = true; } async function save() { saveQueue = saveQueue.then(() => fs.writeFile(storePath, `${JSON.stringify(records, null, 2)}\n`, 'utf8')); return saveQueue; }
const day = (ms = Date.now()) => new Date(ms).toISOString().slice(0, 10); const clean = (s) => s.trim().replace(/[\r\n]/g, ' ').replace(/\s+/g, ' '); const mine = (id) => Object.values(records).find(c => c.memberIds.includes(id)); const validPrice = p => Number.isSafeInteger(p) && p > 0;
function calculateProductDailyRevenue(product, randomInt = crypto.randomInt) { const [min, max] = LEVEL_RANGES[product.level] || LEVEL_RANGES[1]; const baseUnits = min + randomInt(max - min + 1); const multiplier = product.price <= 25 ? 1.2 : product.price <= 100 ? 1 : product.price <= 250 ? .75 : product.price <= 500 ? .5 : .25; const unitsSold = Math.floor(baseUnits * multiplier); return { unitsSold, price: product.price, revenue: unitsSold * product.price, baseUnits, multiplier }; }
async function create(userId, name) { await load(); return lock('global', async () => { if (mine(userId)) return { error: 'member' }; const n = clean(name); if (n.length < 2 || n.length > 60) return { error: 'name' }; const c = { id: crypto.randomUUID(), name: n, ownerId: userId, memberIds: [userId], members: { [userId]: 'OWNER' }, treasury: 0, products: [], invitations: {}, workDays: {}, createdAt: Date.now() }; records[c.id] = c; await save(); return { company: c }; }); }
async function invite(userId, targetId) { await load(); return lock('global', async () => { const c = mine(userId); if (!c || c.ownerId !== userId || mine(targetId)) return { error: 'permission' }; c.invitations[targetId] = { invitedAt: Date.now(), status: 'pending' }; await save(); return { company: c }; }); }
async function join(userId) { await load(); return lock('global', async () => { if (mine(userId)) return { error: 'member' }; const c = Object.values(records).find(x => x.invitations[userId]?.status === 'pending'); if (!c) return { error: 'invite' }; c.invitations[userId].status = 'accepted'; c.memberIds.push(userId); c.members[userId] = 'WORKER'; await save(); return { company: c }; }); }
async function leave(userId) { await load(); return lock('global', async () => { const c = mine(userId); if (!c) return { error: 'none' }; if (c.ownerId === userId) return { error: 'owner' }; c.memberIds = c.memberIds.filter(x => x !== userId); delete c.members[userId]; await save(); return { company: c }; }); }
async function work(userId) { await load(); const c = mine(userId); if (!c) return { error: 'none' }; return lock(c.id, async () => { const today = day(); if (c.workDays[userId] === today) return { error: 'worked' }; if (c.treasury < SALARY) return { error: 'funds', treasury: c.treasury }; c.treasury -= SALARY; try { await economy.addFish(userId, SALARY); c.workDays[userId] = today; await save(); logger.info(`[COMPANY_SALARY] company=${c.id} user=${userId} amount=100 day=${today}`); return { company: c }; } catch (e) { c.treasury += SALARY; throw e; } }); }
async function deposit(userId, amount) { await load(); const c = mine(userId); if (!c || c.ownerId !== userId) return { error: 'owner' }; if (!Number.isSafeInteger(amount) || amount < 1) return { error: 'amount' }; return lock(c.id, async () => { const balance = await economy.getFishBalance(userId); if (amount > balance) return { error: 'funds', balance }; const before = c.treasury; c.treasury += amount; try { await economy.removeFish(userId, amount); await save(); logger.info(`[COMPANY_DEPOSIT] company=${c.id} user=${userId} amount=${amount} treasury=${c.treasury}`); return { company: c, balance: balance - amount }; } catch (e) { c.treasury = before; throw e; } }); }
async function productCreate(userId, name, price) { await load(); const c = mine(userId); const n = clean(name); if (!c || n.length < 2 || n.length > 60 || !validPrice(price)) return { error: 'invalid' }; const creationCost = price * 10; if (!Number.isSafeInteger(creationCost)) return { error: 'invalid' }; return lock(c.id, async () => { const today = day(); if (c.products.some(p => p.createdDayUtc === today)) return { error: 'daily' }; if (c.treasury < creationCost) return { error: 'funds', treasury: c.treasury, cost: creationCost }; c.treasury -= creationCost; const product = { id: crypto.randomUUID(), companyId: c.id, creatorId: userId, name: n, price, level: 1, createdDayUtc: today, createdAt: Date.now() }; try { c.products.push(product); await save(); return { product, cost: creationCost, treasury: c.treasury }; } catch (e) { c.treasury += creationCost; throw e; } }); }
async function triggerRevenue(actorId) { await load(); let products = 0; let revenue = 0; const totals = []; for (const c of Object.values(records)) await lock(c.id, async () => { let total = 0; for (const p of c.products) { const r = calculateProductDailyRevenue(p); c.treasury += r.revenue; total += r.revenue; products++; } revenue += total; totals.push({ companyId: c.id, revenue: total }); if (total) await save(); logger.info(`[COMPANY_REVENUE_ADMIN_TRIGGER] actor=${actorId} company=${c.id} revenue=${total} products=${c.products.length}`); }); return { companies: Object.keys(records).length, products, revenue, totals }; }
async function get(userId) { await load(); return mine(userId); } module.exports = { create, invite, join, leave, work, deposit, productCreate, triggerRevenue, get, calculateProductDailyRevenue, day, SALARY, LEVEL_RANGES };
