const fs=require('node:fs/promises'); const path=require('node:path'); const economy=require('./economy'); const logger=require('./utils/logger');
const storePath=path.join(__dirname,'data','fish-printers.json'); const PRICE=1000; const INK_PRICE=999; let records={};let loaded=false;let queue=Promise.resolve();
const mutate=task=>{const n=queue.then(task,task);queue=n.catch(()=>{});return n;}; async function load(){if(loaded)return;try{records=JSON.parse(await fs.readFile(storePath,'utf8'));}catch{records={};}loaded=true;} async function save(){await fs.writeFile(storePath,`${JSON.stringify(records,null,2)}\n`);} function record(id){return records[id]||=({ownerId:id,owned:false,printAttempts:0,ink:0,fishPrinted:0});}
async function get(id){await load();return {...(records[id]||{ownerId:id,owned:false,printAttempts:0,ink:0,fishPrinted:0})};}
async function buy(id){return mutate(async()=>{await load();const r=record(id);if(r.owned)return{error:'owned',record:r};const balance=await economy.getFishBalance(id);if(balance<PRICE)return{error:'funds',balance};await economy.removeFish(id,PRICE);r.owned=true;r.purchasedAt=Date.now();try{await save();logger.info(`[FISH_PRINTER_PURCHASE] userId=${id}`);return{record:r,balance:balance-PRICE};}catch(e){r.owned=false;delete r.purchasedAt;await economy.addFish(id,PRICE);throw e;}});}
async function buyInk(id){return mutate(async()=>{await load();const r=record(id);const balance=await economy.getFishBalance(id);if(balance<INK_PRICE)return{error:'funds',balance};await economy.removeFish(id,INK_PRICE);r.ink=(r.ink||0)+1;try{await save();return{record:r,balance:balance-INK_PRICE};}catch(e){r.ink-=1;await economy.addFish(id,INK_PRICE);throw e;}});}
async function print(id){return mutate(async()=>{await load();const r=record(id);if(!r.owned)return{error:'unowned'};if(!(r.ink>0))return{error:'ink'};const old={...r};r.printAttempts+=1;r.ink-=1;r.fishPrinted=(r.fishPrinted||0)+1;await economy.addFish(id,1);try{await save();return{success:true,attempts:r.printAttempts,ink:r.ink,fishPrinted:r.fishPrinted,message:'🖨️ **SUCCESS!**\n\n🐟 +1 Fish'};}catch(e){Object.assign(r,old);await economy.removeFish(id,1);throw e;}});}
async function grant(id,kind,quantity=1){return mutate(async()=>{await load();const r=record(id);if(kind==='printer'){if(r.owned)throw new Error('owned');r.owned=true;}else r.ink=(r.ink||0)+quantity;await save();return r;});}
module.exports={get,buy,buyInk,grant,print,PRICE,INK_PRICE};
