const fs = require('node:fs/promises'); const path = require('node:path'); const economy = require('./economy'); const logger = require('./utils/logger');
const storePath = path.join(__dirname, 'data', 'fish-printers.json'); const PRICE = 1000; let records = {}; let loaded = false; let queue = Promise.resolve();
const mutate = task => { const next = queue.then(task, task); queue = next.catch(() => {}); return next; };
async function load() { if (loaded) return; try { records = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { records = {}; } loaded = true; } async function save() { await fs.writeFile(storePath, `${JSON.stringify(records, null, 2)}\n`, 'utf8'); }
function record(userId) { return records[userId] ||= { ownerId: userId, owned: false, printAttempts: 0 }; }
const messages = [ '🖨️ PRINTING FISH...\n\n██████████ 100%\n\n+0 🐟\n\nnice try.', '🖨️ FISH PRINTER™\n\nWarming up...\nChecking ink...\nContacting Fish Reserve...\nRequest denied.\n\nFish printed: 0 🐟\n\nnice try.', '🖨️ PRINT JOB COMPLETE\n\nPaper loaded: ✅\nInk loaded: ✅\nFish loaded: ❌\n\nOutput:\n0 🐟\n\nnice try.', '🖨️ FishPrinter.exe\n\nGenerating fish...\nGenerating fish...\nGenerating fish...\n\nERROR:\nFish are not printable.\n\n+0 🐟' ];
async function get(userId) { await load(); return { ...(records[userId] || { ownerId: userId, owned: false, printAttempts: 0 }) }; }
async function buy(userId) { return mutate(async () => { await load(); const r = record(userId); if (r.owned) return { error: 'owned', record: r }; const balance = await economy.getFishBalance(userId); if (balance < PRICE) return { error: 'funds', balance }; await economy.removeFish(userId, PRICE); r.owned = true; r.purchasedAt = Date.now(); try { await save(); logger.info(`[FISH_PRINTER_PURCHASE] userId=${userId} price=${PRICE} timestamp=${new Date(r.purchasedAt).toISOString()}`); return { record: r, balance: balance - PRICE }; } catch (e) { r.owned = false; delete r.purchasedAt; await economy.addFish(userId, PRICE); throw e; } }); }
async function print(userId) { return mutate(async () => { await load(); const r = record(userId); if (!r.owned) return { error: 'unowned' }; r.printAttempts += 1; await save(); return { attempts: r.printAttempts, message: r.printAttempts === 10 ? '🖨️ 10 print attempts.\n\nFish printed:\n0\n\nPerhaps attempt #11 will work.\n\n(It won’t.)' : r.printAttempts === 100 ? '🖨️ 100 PRINT ATTEMPTS\n\nTotal fish printed:\n0 🐟\n\nThe engineering department has been notified.' : r.printAttempts === 1000 ? '🏆 FISH PRINTER MILESTONE\n\n1,000 print attempts.\n\nFish produced:\n0\n\nEfficiency: 0%' : messages[(r.printAttempts - 1) % messages.length] }; }); }
module.exports = { get, buy, print, PRICE };
