const fs = require('node:fs/promises'); const path = require('node:path'); const economy = require('./economy'); const logger = require('./utils/logger');
const storePath = path.join(__dirname, 'data', 'fridges.json'); const MAX_ACTIVITY = 20; let records = {}; let loaded = false; const locks = new Map(); let saveQueue = Promise.resolve();
function lock(id, task) { const p = locks.get(id) || Promise.resolve(); const c = p.then(task, task); locks.set(id, c); c.finally(() => { if (locks.get(id) === c) locks.delete(id); }).catch(() => {}); return c; }
async function load() { if (loaded) return; try { records = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { records = {}; } loaded = true; } async function save() { saveQueue = saveQueue.then(() => fs.writeFile(storePath, `${JSON.stringify(records, null, 2)}\n`, 'utf8')); return saveQueue; }
function state(id) { return records[id] ||= { guildId: id, balance: 0, recentActivity: [] }; } const validAmount = n => Number.isSafeInteger(n) && n > 0; function activity(f, type, userId, amount) { f.recentActivity.push({ type, userId, amount, timestamp: Date.now() }); f.recentActivity = f.recentActivity.slice(-MAX_ACTIVITY); }
async function view(guildId) { await load(); const f = state(guildId); return { balance: f.balance, recentActivity: [...f.recentActivity] }; }
async function put(guildId, userId, amount, theft) { if (!validAmount(amount)) return { error: 'amount' }; if (await theft.hasActiveTheftAsThief(userId)) return { error: 'theft' }; return lock(guildId, async () => { await load(); const f = state(guildId); const wallet = await economy.getFishBalance(userId); if (amount > wallet) return { error: 'funds' }; if (!Number.isSafeInteger(f.balance + amount)) return { error: 'overflow' }; const before = f.balance; await economy.removeFish(userId, amount); f.balance += amount; activity(f, 'PUT', userId, amount); try { await save(); logger.info(`[FRIDGE_PUT] guild=${guildId} user=${userId} amount=${amount} balance=${f.balance}`); return { balance: f.balance }; } catch (e) { f.balance = before; await economy.addFish(userId, amount); throw e; } }); }
async function take(guildId, userId, amount) { if (!validAmount(amount)) return { error: 'amount' }; return lock(guildId, async () => { await load(); const f = state(guildId); if (amount > f.balance) return { error: 'funds', balance: f.balance }; const wallet = await economy.getFishBalance(userId); if (wallet > Number.MAX_SAFE_INTEGER - amount) return { error: 'overflow' }; const before = f.balance; await economy.addFish(userId, amount); f.balance -= amount; activity(f, 'TAKE', userId, amount); try { await save(); logger.info(`[FRIDGE_TAKE] guild=${guildId} user=${userId} amount=${amount} balance=${f.balance}`); return { balance: f.balance, wallet: wallet + amount }; } catch (e) { f.balance = before; await economy.removeFish(userId, amount); throw e; } }); }
async function takeAll(guildId, userId) { return lock(guildId, async () => { await load(); const f = state(guildId); const amount = f.balance; if (!amount) return { error: 'empty' }; const wallet = await economy.getFishBalance(userId); if (wallet > Number.MAX_SAFE_INTEGER - amount) return { error: 'overflow' }; await economy.addFish(userId, amount); f.balance = 0; activity(f, 'TAKE_ALL', userId, amount); try { await save(); logger.info(`[FRIDGE_TAKE_ALL] guild=${guildId} user=${userId} amount=${amount}`); return { amount, balance: 0, wallet: wallet + amount }; } catch (e) { f.balance = amount; await economy.removeFish(userId, amount); throw e; } }); }
module.exports = { view, put, take, takeAll, validAmount, MAX_ACTIVITY };
