const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const config = require('./config'); const logger = require('./utils/logger');
const storePath = path.join(__dirname, 'data', 'inbox.json'); let state = {}; let loaded = false; const locks = new Map(); const cooldowns = new Map();
async function load() { if (loaded) return; try { state = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { state = {}; } loaded = true; }
async function save() { await fs.writeFile(storePath, `${JSON.stringify(state, null, 2)}\n`, 'utf8'); }
function lock(id, task) { const p = (locks.get(id) || Promise.resolve()).then(task, task); locks.set(id, p); p.finally(() => locks.get(id) === p && locks.delete(id)).catch(() => {}); return p; }
function clean(value) { return String(value || '').replace(/@(everyone|here|&?\d+|!?\d+)/gi, '@﹫'); }
function create(data) { return { id: crypto.randomBytes(12).toString('hex'), recipientId: data.recipientId, senderId: data.senderId || null, type: data.type || 'system', title: clean(data.title || 'Igloo Notification'), message: clean(data.message), metadata: data.metadata || {}, createdAt: new Date().toISOString(), read: false, saved: false, deleted: false }; }
async function send(data) { await load(); return lock(data.recipientId, async () => { const item = create(data); state[data.recipientId] ||= []; state[data.recipientId].push(item); await save(); if (data.tryDM !== false && data.client) { try { const user = await data.client.users.fetch(data.recipientId); const sender = item.senderId ? `<@${item.senderId}>` : 'PengBot'; const embed = new EmbedBuilder().setColor(0x6bd6e8).setTitle(`${config.pengEmoji()} ${item.title}`).setDescription(`From: ${sender}\n\n${item.message}`).setTimestamp(new Date(item.createdAt)); await user.send({ embeds: [embed], components: item.type === 'mail' && item.senderId ? [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`inbox_reply:${item.id}`).setLabel('Reply').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId(`inbox_save:${item.id}`).setLabel('Save').setStyle(ButtonStyle.Secondary))] : [], allowedMentions: { parse: [] } }); item.dmDelivered = true; await save(); } catch (error) { logger.error(`Inbox DM delivery failed for ${item.id}`, error); } } logger.info(`Inbox notification generated id=${item.id} recipient=${item.recipientId} type=${item.type}`); return item; }); }
async function list(userId, unreadOnly = false) { await load(); return (state[userId] || []).filter((x) => !x.deleted && (!unreadOnly || !x.read)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
async function get(userId, id) { await load(); return (state[userId] || []).find((x) => x.id === id && !x.deleted) || null; }
async function update(userId, id, changes) { await load(); return lock(userId, async () => { const item = (state[userId] || []).find((x) => x.id === id); if (!item || item.deleted) return null; Object.assign(item, changes); await save(); return item; }); }
function cooldown(userId) { const next = cooldowns.get(userId) || 0; if (Date.now() < next) return false; cooldowns.set(userId, Date.now() + 15000); return true; }
function render(item, index, total) { return new EmbedBuilder().setColor(item.read ? 0x747f8d : 0x6bd6e8).setTitle(`${config.pengEmoji()} ${item.title}`).setDescription(`${item.read ? '📭 Read' : '📬 Unread'} · ${item.type}\n\n${item.message}`).addFields({ name: 'From', value: item.senderId ? `<@${item.senderId}>` : 'PengBot' }, { name: 'Received', value: `<t:${Math.floor(new Date(item.createdAt).getTime() / 1000)}:R>` }).setFooter({ text: `${index + 1}/${total}${item.saved ? ' · Saved' : ''}` }); }
function controls(item, index, total) { return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`inbox_prev:${item.recipientId}:${index}`).setLabel('Previous').setStyle(ButtonStyle.Secondary).setDisabled(index <= 0), new ButtonBuilder().setCustomId(`inbox_next:${item.recipientId}:${index}`).setLabel('Next').setStyle(ButtonStyle.Secondary).setDisabled(index >= total - 1), new ButtonBuilder().setCustomId(`inbox_read:${item.id}`).setLabel('Mark Read').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId(`inbox_save:${item.id}`).setLabel(item.saved ? 'Unsave' : 'Save').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`inbox_delete:${item.id}`).setLabel('Delete').setStyle(ButtonStyle.Danger))]; }
module.exports = { send, list, get, update, cooldown, render, controls };
