const crypto = require('node:crypto');
const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const config = require('./config'); const economy = require('./economy'); const ktv = require('./ktv-manager'); const logger = require('./utils/logger');
const pending = new Map(); const locks = new Map(); const TTL = 10 * 60 * 1000;
function lock(userId, task) { const previous = locks.get(userId) || Promise.resolve(); const current = previous.then(task, task); locks.set(userId, current); current.finally(() => { if (locks.get(userId) === current) locks.delete(userId); }).catch(() => {}); return current; }
function expire(id) { const item = pending.get(id); if (item && Date.now() >= item.expiresAt) pending.delete(id); }
function confirmPanel(id, balance) { const price = config.ktvRentalPrice(); return { embeds: [new EmbedBuilder().setColor(0xf4c95d).setTitle('🏢 PIKAPENG REAL ESTATE').setDescription(`🎤 **Private KTV Rental**\n\nRental Fee:\n🐟 **${price} Fish**\n\nYour Wallet:\n🐟 **${balance} Fish**\n\nAfter Payment:\n🐟 **${balance - price} Fish**\n\nLease Duration:\nUntil everybody leaves.\n\nIncludes:\n🔒 Private KTV\n🔔 Doorbell invitations\n🔑 KTV management\n👥 Guest access controls\n\nPikaPeng requires payment before handing over the keys.`)], components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`ktv_pay:${id}`).setLabel(`🐟 PAY ${price} FISH & RENT`).setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`ktv_cancel_rent:${id}`).setLabel('❌ CANCEL').setStyle(ButtonStyle.Secondary))] }; }
async function begin(i) { return lock(i.user.id, async () => { if (await ktv.getOwnedRoom(i.guild, i.user.id)) return { existing: true }; const balance = await economy.getFishBalance(i.user.id); const price = config.ktvRentalPrice(); if (balance < price) return { insufficient: true, balance }; const id = crypto.randomBytes(12).toString('hex'); pending.set(id, { id, userId: i.user.id, guildId: i.guild.id, expiresAt: Date.now() + TTL }); setTimeout(() => expire(id), TTL); return { id, balance }; }); }
async function pay(i, id) { expire(id); const item = pending.get(id); if (!item || item.guildId !== i.guildId) return i.reply({ content: '🏚️ This KTV rental confirmation has expired.', ephemeral: true }); if (item.userId !== i.user.id) return i.reply({ content: '🐧 This rental confirmation belongs to someone else.', ephemeral: true }); return lock(item.userId, async () => { if (!pending.has(id)) return i.reply({ content: '🏚️ This KTV rental confirmation has expired.', ephemeral: true }); if (await ktv.getOwnedRoom(i.guild, item.userId)) { pending.delete(id); return i.update({ content: '🐧 You already own a PikaPeng KTV.', embeds: [], components: [] }); } const price = config.ktvRentalPrice(); const balance = await economy.getFishBalance(item.userId); if (balance < price) { pending.delete(id); return i.update({ content: `🏢 PikaPeng Real Estate\n\n❌ INSUFFICIENT FISH\n\nYour wallet now has **${balance} 🐟**. Use \`/fish\` and try again.`, embeds: [], components: [] }); } try { await economy.removeFish(item.userId, price); let room; try { room = await ktv.createRoom(i, { skipLock: true }); } catch (error) { try { await economy.addFish(item.userId, price); } catch (refundError) { logger.error(`CRITICAL KTV refund failure for ${item.userId}`, refundError); pending.delete(id); return i.update({ content: '🐧 PikaPeng could not finish the rental and could not confirm the refund. Please contact staff.', embeds: [], components: [] }); } logger.error('KTV creation failed after payment', error); pending.delete(id); return i.update({ content: `🐧 PikaPeng couldn't finish your KTV rental.\n\nYour **${price} Fish have been refunded**.\n\nNo KTV rental was created.`, embeds: [], components: [] }); } pending.delete(id); const remaining = await economy.getFishBalance(item.userId); return i.update({ content: `🔑 RENTAL APPROVED!\n\n🏢 PikaPeng Real Estate\n\n🎤 ${room.channel}\n\n🐟 Rental Fee: **${price} Fish**\n👛 Remaining Balance: **${remaining} Fish**\n\n🔒 Your KTV is private.\nUse \`/doorbell @user\` to invite guests.\n\nYour rental automatically ends when everybody leaves.\n\n🐧 PikaPeng has eaten your payment.`, embeds: [], components: [] }); } catch (error) { logger.error(`KTV payment failed for ${item.userId}`, error); return i.reply({ content: '🐧 PikaPeng could not complete the payment. No KTV was created.', ephemeral: true }); } }); }
function cancel(i, id) { const item = pending.get(id); if (!item || item.userId !== i.user.id) return i.reply({ content: '🏚️ This KTV rental confirmation has expired.', ephemeral: true }); pending.delete(id); return i.update({ content: '❌ KTV RENTAL CANCELLED\n\n🐟 Fish charged: **0**\n\nPikaPeng has reluctantly returned the keys to the drawer. 🐧', embeds: [], components: [] }); }
module.exports = { begin, pay, cancel, confirmPanel };
