const http = require('node:http'); const crypto = require('node:crypto'); const fs = require('node:fs/promises'); const path = require('node:path');
const config = require('./config'); const logger = require('./utils/logger');
const storePath = path.join(__dirname, 'data', 'oauth-users.json'); let users = {}; let loaded = false; const states = new Map();
async function load() { if (loaded) return; try { users = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { users = {}; } loaded = true; }
async function save() { await fs.writeFile(storePath, `${JSON.stringify(users, null, 2)}\n`, 'utf8'); }
function authUrl(userId) { const state = crypto.randomBytes(24).toString('hex'); states.set(state, { userId, expires: Date.now() + 600000 }); const params = new URLSearchParams({ response_type: 'code', client_id: config.clientId(), scope: 'identify guilds guilds.join', redirect_uri: config.oauthRedirectUri(), state, prompt: 'consent' }); return `https://discord.com/oauth2/authorize?${params}`; }
async function exchange(code) { const body = new URLSearchParams({ grant_type: 'authorization_code', code, redirect_uri: config.oauthRedirectUri() }); const basic = Buffer.from(`${config.clientId()}:${config.oauthClientSecret()}`).toString('base64'); const response = await fetch('https://discord.com/api/v10/oauth2/token', { method: 'POST', headers: { Authorization: `Basic ${basic}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body }); if (!response.ok) throw new Error(`OAuth exchange failed: ${response.status}`); return response.json(); }
async function getToken(userId) { await load(); return users[userId]?.accessToken || null; }
async function userGuildIds(userId) { const token = await getToken(userId); if (!token) return []; const response = await fetch('https://discord.com/api/v10/users/@me/guilds', { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) return []; return (await response.json()).map((guild) => guild.id); }
async function joinGuild(userId, guildId) { const token = await getToken(userId); if (!token) return false; const response = await fetch(`https://discord.com/api/v10/guilds/${guildId}/members/${userId}`, { method: 'PUT', headers: { Authorization: `Bot ${config.token()}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ access_token: token }) }); return response.ok || response.status === 204; }
function startServer() { if (!config.oauthClientSecret() || !config.oauthRedirectUri()) { logger.info('Discord OAuth is disabled: OAUTH_CLIENT_SECRET or OAUTH_REDIRECT_URI is not configured.'); return; } const target = new URL(config.oauthRedirectUri()); http.createServer(async (request, response) => { try { const url = new URL(request.url, `http://${request.headers.host}`); if (url.pathname !== target.pathname) { response.writeHead(404); return response.end('Not found'); } const session = states.get(url.searchParams.get('state')); states.delete(url.searchParams.get('state')); if (!session || session.expires < Date.now()) { response.writeHead(400); return response.end('OAuth session expired.'); } const token = await exchange(url.searchParams.get('code')); const identityResponse = await fetch('https://discord.com/api/v10/users/@me', { headers: { Authorization: `Bearer ${token.access_token}` } }); const identity = await identityResponse.json(); await load(); users[session.userId] = { accessToken: token.access_token, refreshToken: token.refresh_token, expiresAt: Date.now() + token.expires_in * 1000, discordUserId: identity.id, updatedAt: new Date().toISOString() }; await save(); response.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' }); response.end('<h1>PikaPeng permissions connected</h1><p>Return to Discord and use /travel.</p>'); } catch (error) { logger.error('OAuth callback failed', error); response.writeHead(500); response.end('OAuth setup failed.'); } }).listen(config.oauthPort(), config.oauthHost(), () => logger.info(`Discord OAuth callback listening on ${config.oauthHost()}:${config.oauthPort()}`)); }
setImmediate(startServer);
module.exports = { authUrl, userGuildIds, joinGuild, startServer };
