const fs = require('node:fs/promises'); const path = require('node:path'); const crypto = require('node:crypto'); const { ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const economy = require('./economy'); const config = require('./config'); const logger = require('./utils/logger');
const storePath = path.join(__dirname, 'data', 'pikapeng-irs.json'); const DEADLINE = 60000; const activeStatuses = new Set(['PENDING_DELIVERY', 'AWAITING_PAYMENT']); const blocked = new Set(['fish', 'fishprinter', 'gamble', 'coinflip', 'work', 'waddle', 'company', 'bank', 'ram', 'fridge', 'contribute']);
function calculate(balance) { return { balanceAtAssessment: balance, normalTax: Math.floor(balance * 0.10), jailTax: Math.floor(balance * 0.20) }; }
let state = { cases: {}, lastAssessmentAt: 0 }; let loaded = false; let queue = Promise.resolve(); const timers = new Map();
async function load() { if (loaded) return; try { state = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { state = { cases: {}, lastAssessmentAt: 0 }; } state.cases ||= {}; loaded = true; }
async function save() { await fs.mkdir(path.dirname(storePath), { recursive: true }); const temp = `${storePath}.tmp`; await fs.writeFile(temp, `${JSON.stringify(state, null, 2)}\n`); await fs.rename(temp, storePath); }
function mutate(fn) { const next = queue.then(async () => { await load(); return fn(); }); queue = next.catch(() => {}); return next; }
function caseFor(userId) { return Object.values(state.cases).find(c => c.userId === userId && activeStatuses.has(c.status)); }
function notice(c) { return { content: `? Before you waddle?吒n\n?屁 **YOU HAVE OUTSTANDING TAXES.**\n\nThe Igloo Revenue Service has been trying to reach you.\n\nBalance at assessment: ?? **${c.balanceAtAssessment.toLocaleString()}**\nTax due: ?? **${c.normalTax.toLocaleString()}**\n\n?梧? You have 60 seconds.`, components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`irs_pay:${c.caseId}`).setLabel('PAY TAX').setStyle(ButtonStyle.Success), new ButtonBuilder().setCustomId(`irs_refuse:${c.caseId}`).setLabel('I REFUSE').setStyle(ButtonStyle.Danger))], ephemeral: true }; }
function dmNotice(c) { return { content: `?屁 **PIKAPENG IRS ??RESTART TAX**\n\nThe Igloo Revenue Service has detected an IglooBot restart.\n\nBalance at assessment: ?? **${c.balanceAtAssessment.toLocaleString()}**\nTax due: ?? **${c.normalTax.toLocaleString()} (10%)**\n\nYou have 60 seconds to respond.`, components: notice(c).components }; }
function schedule(c) { if (c.status !== 'AWAITING_PAYMENT' || !c.deadlineAt) return; const delay = Math.max(0, c.deadlineAt - Date.now()); clearTimeout(timers.get(c.caseId)); const timer = setTimeout(() => resolve(c.caseId, 'DEFAULTED').catch(error => logger.error(`IRS timeout failed case=${c.caseId}: ${error.message}`)), delay); timer.unref?.(); timers.set(c.caseId, timer); }
async function collect(c, amount, type) { const balance = await economy.getFishBalance(c.userId); const taken = Math.min(balance, amount); if (taken > 0) await economy.removeFish(c.userId, taken); c.amountPaid = (c.amountPaid || 0) + taken; c.remainingDebt = Math.max(0, amount - taken); logger.info(`IRS collection type=${type} user=${c.userId} case=${c.caseId} amount=${taken}`); return taken; }
async function resolve(caseId, outcome) { return mutate(async () => { const c = state.cases[caseId]; if (!c || !activeStatuses.has(c.status)) return c; c.status = outcome; c.resolvedAt = Date.now(); clearTimeout(timers.get(caseId)); timers.delete(caseId); const amount = outcome === 'PAID' ? c.normalTax : c.jailTax; await collect(c, amount, outcome === 'PAID' ? 'PIKAPENG_IRS_TAX' : 'PIKAPENG_IRS_PENALTY'); if (outcome !== 'PAID') c.jailed = true; await save(); logger.info(`IRS case ${outcome.toLowerCase()} user=${c.userId} case=${c.caseId}`); return c; }); }
async function assess(client) { if (!config.pikaPengIrsEnabled()) return; await load(); const now = Date.now(); const minimum = config.pikaPengIrsMinRestartIntervalSeconds() * 1000; if (minimum > 0 && now - state.lastAssessmentAt < minimum) return; state.lastAssessmentAt = now; await save(); for (const userId of await economy.getPositiveBalanceUserIds()) { if (caseFor(userId)) continue; const user = await client.users.fetch(userId).catch(() => null); if (user?.bot) continue; const balance = await economy.getFishBalance(userId); if (balance <= 0) continue; const c = { caseId: crypto.randomUUID(), userId, balanceAtAssessment: balance, normalTax: Math.floor(balance * 0.10), jailTax: Math.floor(balance * 0.20), status: 'PENDING_DELIVERY', createdAt: now, deliveredAt: null, deadlineAt: null, deliveryMethod: null, amountPaid: 0, remainingDebt: 0, jailed: false, resolvedAt: null }; state.cases[c.caseId] = c; await save(); logger.info(`IRS case created user=${userId} case=${c.caseId}`); try { await user.send(dmNotice(c)); c.status = 'AWAITING_PAYMENT'; c.deliveredAt = Date.now(); c.deadlineAt = c.deliveredAt + DEADLINE; c.deliveryMethod = 'dm'; await save(); schedule(c); logger.info(`IRS notice delivered user=${userId} method=dm`); } catch (error) { await save(); logger.info(`IRS notice pending delivery user=${userId} case=${c.caseId}`); } } }
async function startup(client) { await load(); for (const c of Object.values(state.cases)) { if (c.status === 'AWAITING_PAYMENT' && c.deadlineAt <= Date.now()) await resolve(c.caseId, 'DEFAULTED'); else schedule(c); } await assess(client); }
async function interceptCommand(i) { if (!config.pikaPengIrsEnabled() || !i.isChatInputCommand()) return false; const c = await mutate(async () => caseFor(i.user.id)); if (!c) return false; await i.reply(notice(c)); const fresh = await mutate(async () => { const current = state.cases[c.caseId]; if (current.status === 'PENDING_DELIVERY') { current.status = 'AWAITING_PAYMENT'; current.deliveredAt = Date.now(); current.deadlineAt = current.deliveredAt + DEADLINE; current.deliveryMethod = 'ephemeral'; await save(); schedule(current); } return current; }); return Boolean(fresh); }
async function handleButton(i, action, caseId) { await load(); return (async () => { const c = state.cases[caseId]; if (!c || c.userId !== i.user.id || !activeStatuses.has(c.status)) return i.reply({ content: '?屁 This IRS case is already resolved or does not belong to you.', ephemeral: true }); if (c.status === 'AWAITING_PAYMENT' && c.deadlineAt <= Date.now()) { await resolve(caseId, 'DEFAULTED'); return i.update({ content: '? PIKAPENG IRS ??FINAL NOTICE\n\nPayment deadline expired.\n\n?? You have been sent to PikaPeng Jail.', components: [] }); } const outcome = action === 'pay' ? 'PAID' : 'REFUSED'; const resolved = await resolve(caseId, outcome); if (outcome === 'PAID') return i.update({ content: `??**TAXES PAID**\n\nPaid: ?? ${resolved.amountPaid.toLocaleString()}\n\nPikaPeng has determined that you are currently in acceptable standing.`, components: [] }); return i.update({ content: `? **TAX EVASION DETECTED**\n\nOriginal tax rate: 10%\nPenalty rate: 20% TOTAL\n\n?? Seized: ${resolved.amountPaid.toLocaleString()}\n\n?? You have been sent to PikaPeng Jail.\n\nCrime: Refusing to give a penguin 10% of your fish.`, components: [] }); })(); }
function isUserJailed(userId) { const c = Object.values(state.cases).find(x => x.userId === userId && x.jailed); return Boolean(c); }
function canUseCommandWhileJailed(name) { return !blocked.has(name); }
async function pending(userId) { return mutate(async () => caseFor(userId)); }
module.exports = { calculate, startup, interceptCommand, handleButton, isUserJailed, canUseCommandWhileJailed, pending, resolve, _resetForTests: async () => { state = { cases: {}, lastAssessmentAt: 0 }; loaded = true; queue = Promise.resolve(); } };
