const fs=require('node:fs/promises');const path=require('node:path');const crypto=require('node:crypto');const economy=require('./economy');
const file=path.join(__dirname,'data','pika-captcha.json');let state={users:{}};let loaded=false;let q=Promise.resolve();const sessions=new Map();
async function load(){if(loaded)return;try{state=JSON.parse(await fs.readFile(file,'utf8'));}catch{}state.users||={};loaded=true;}async function save(){await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(`${file}.tmp`,JSON.stringify(state,null,2));await fs.rename(`${file}.tmp`,file);}function mutate(fn){const n=q.then(async()=>{await load();return fn()});q=n.catch(()=>{});return n;}
function user(id){return state.users[id]||=( {owned:false,started:0,solved:0,failed:0,currentStreak:0,bestStreak:0,fastest:null} );}
async function buy(id){return mutate(async()=>{const u=user(id);if(u.owned)return{error:'owned'};const b=await economy.getFishBalance(id);if(b<500)return{error:'funds',balance:b};await economy.removeFish(id,500);u.owned=true;await save();return{ok:true};});}
async function get(id){await load();return{...user(id)};}function start(id){const u=state.users[id];if(!u?.owned)return null;const answer=[0,4,7];const token=crypto.randomUUID();sessions.set(token,{id,owner:id,answer,selected:[],started:Date.now(),finished:false});u.started++;save();return{token,answer};}
async function toggle(token,index){const s=sessions.get(token);if(!s||s.finished)return null;if(!s.selected.includes(index))s.selected.push(index);else s.selected=s.selected.filter(x=>x!==index);return s;}
async function verify(token){return mutate(async()=>{const s=sessions.get(token);if(!s||s.finished)return null;s.finished=true;const u=user(s.owner);const ok=s.selected.length===s.answer.length&&s.selected.every(x=>s.answer.includes(x));const elapsed=(Date.now()-s.started)/1000;if(ok){u.solved++;u.currentStreak++;u.bestStreak=Math.max(u.bestStreak,u.currentStreak);if(u.fastest===null||elapsed<u.fastest)u.fastest=elapsed;}else{u.failed++;u.currentStreak=0;}await save();return{ok,elapsed,streak:u.currentStreak,selected:s.selected.length,correct:s.answer.length};});}
module.exports={buy,get,start,toggle,verify,session:t=>sessions.get(t),_resetForTests:async()=>{state={users:{}};loaded=true;q=Promise.resolve();sessions.clear();}};
