const fs=require('node:fs/promises'); const path=require('node:path'); const crypto=require('node:crypto'); const economy=require('./economy'); const config=require('./config');
const file=path.join(__dirname,'data','pikacourt.json'); let state={next:1,cases:{},service:{}}; let loaded=false; let q=Promise.resolve();
async function load(){if(loaded)return;try{state={...state,...JSON.parse(await fs.readFile(file,'utf8'))};}catch{} state.cases||={};state.service||={};loaded=true;}
async function save(){await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(`${file}.tmp`,JSON.stringify(state,null,2));await fs.rename(`${file}.tmp`,file);}
function mutate(fn){const n=q.then(async()=>{await load();return fn()});q=n.catch(()=>{});return n;}
function judge(id){return config.pikaCourtJudgeId()&&id===config.pikaCourtJudgeId();} function clean(s){return String(s||'').replace(/@(everyone|here|&?\d+)/gi,'@ $1').trim();} function id(){return `PC-${String(state.next++).padStart(4,'0')}`;}
async function fileCase(plaintiff,defendant,claim,damages,statement=''){return mutate(async()=>{if(!config.pikaCourtEnabled())return{error:'disabled'};if(plaintiff===defendant)return{error:'self'};if(!Number.isSafeInteger(damages)||damages<0||damages>config.pikaCourtMaxDamages())return{error:'damages'};const c={caseId:id(),plaintiffId:plaintiff,defendantId:defendant,claim:clean(claim).slice(0,2000),requestedDamages:damages,plaintiffStatement:clean(statement).slice(0,2000),defendantResponse:null,state:'AWAITING_RESPONSE',awardedDamages:0,judgeId:null,createdAt:Date.now(),resolvedAt:null,financialExecuted:false};state.cases[c.caseId]=c;await save();return c;});}
async function respond(user,caseId,text){return mutate(async()=>{const c=state.cases[caseId];if(!c||c.defendantId!==user||c.state!=='AWAITING_RESPONSE')return null;c.defendantResponse=clean(text).slice(0,2000);c.state='READY_FOR_JUDGE';await save();return c;});}
async function resolve(user,caseId,outcome,amount=0){return mutate(async()=>{if(!judge(user))return{error:'judge'};const c=state.cases[caseId];if(!c)return{error:'missing'};if(outcome==='DISMISSED'){if(!['AWAITING_RESPONSE','READY_FOR_JUDGE','UNDER_REVIEW'].includes(c.state))return c;c.state='DISMISSED';c.judgeId=user;c.resolvedAt=Date.now();await save();return c;}if(!['PLAINTIFF_WINS','DEFENDANT_WINS'].includes(outcome)||c.financialExecuted)return c;if(c.state==='CLOSED'||c.state==='DISMISSED')return c;c.state=outcome;c.judgeId=user;c.awardedDamages=outcome==='PLAINTIFF_WINS'?Math.min(amount,c.requestedDamages):0;if(outcome==='PLAINTIFF_WINS'){const have=await economy.getFishBalance(c.defendantId);const taken=Math.min(have,c.awardedDamages);if(taken)await economy.removeFish(c.defendantId,taken);const shortfall=c.awardedDamages-taken;if(c.awardedDamages)await economy.addFish(c.plaintiffId,c.awardedDamages);c.judgment={defendantFishTaken:taken,pikaCourtSupplied:shortfall,plaintiffFishCredited:c.awardedDamages,servicePoints:Math.min(50,Math.ceil(shortfall/10))};if(c.judgment.servicePoints)state.service[`${c.caseId}:${c.defendantId}`]={caseId:c.caseId,userId:c.defendantId,required:c.judgment.servicePoints,completed:0,status:'ACTIVE',createdAt:Date.now()};}c.financialExecuted=true;c.state='CLOSED';c.resolvedAt=Date.now();await save();return c;});}
async function addService(user,points,event){return mutate(async()=>{if(!Number.isSafeInteger(points)||points<1)return 0;let left=points;for(const s of Object.values(state.service).filter(x=>x.userId===user&&x.status==='ACTIVE').sort((a,b)=>a.createdAt-b.createdAt)){if(state.serviceEvents?.[`${event}:${s.caseId}`])continue;state.serviceEvents||={};state.serviceEvents[`${event}:${s.caseId}`]=true;const n=Math.min(left,s.required-s.completed);s.completed+=n;left-=n;if(s.completed>=s.required){s.completed=s.required;s.status='COMPLETED';s.completedAt=Date.now();}if(!left)break;}await save();return points-left;});}
async function service(user){await load();return Object.values(state.service).filter(x=>x.userId===user&&x.status==='ACTIVE');} async function get(caseId){await load();return state.cases[caseId]||null;} async function all(user,judgeOnly=false){await load();return Object.values(state.cases).filter(c=>judgeOnly?judge(user):c.plaintiffId===user||c.defendantId===user);}
module.exports={fileCase,respond,resolve,service,addService,get,all,judge,clean,_resetForTests:async()=>{state={next:1,cases:{},service:{}};loaded=true;q=Promise.resolve();}};
