const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const economy = require('./economy');

const storePath = path.join(__dirname, 'data', 'pika-isp.json');
const GB = 1_000_000_000;
const PLANS = Object.freeze({ fishnet: { name: 'FishNet', downloadMbps: 50, uploadMbps: 20, devices: 4, price: 150 }, fiber: { name: 'Waddle Fiber', downloadMbps: 250, uploadMbps: 100, devices: 8, price: 500 }, gigabit: { name: 'Igloo Gigabit', downloadMbps: 1000, uploadMbps: 500, devices: 16, price: 1500 } });
const GAMES = Object.freeze({ fish_simulator: { id: 'fish_simulator', name: 'Fish Simulator', size: 5 * GB, price: 0, description: 'Catch fish. Collect fish. Question why you are catching Fish when Fish is already the currency.' } });
const SPECIES = ['🐟 Salmon', '🐠 Icefish', '🐡 PufferPeng', '🧊 Frozen Fish', '💾 USB Fish', '✨ Golden Salmon', '🖨️ FishPrinter Cartridge'];
let state = { subscriptions: {}, routers: {}, pcs: {}, licenses: {}, downloads: {}, games: {} }; let loaded = false; let queue = Promise.resolve();
async function load() { if (loaded) return; try { state = { ...state, ...JSON.parse(await fs.readFile(storePath, 'utf8')) }; } catch {} loaded = true; }
async function save() { await fs.mkdir(path.dirname(storePath), { recursive: true }); const tmp = `${storePath}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(state, null, 2)}\n`); await fs.rename(tmp, storePath); }
function mutate(fn) { const next = queue.then(async () => { await load(); return fn(); }); queue = next.catch(() => {}); return next; }
function plan(id) { return PLANS[id]; }
function ensurePc(userId) { if (!state.pcs[userId]) state.pcs[userId] = { userId, name: `${userId}-PC`, capacity: 128 * GB, used: 0, routerId: null }; return state.pcs[userId]; }
function onlineRouter(router) { const sub = state.subscriptions[router.ownerId]; return Boolean(sub && sub.expiresAt > Date.now()); }
function activeDownloads(routerId) { return Object.values(state.downloads).filter(d => d.routerId === routerId && d.status === 'DOWNLOADING'); }
function settle(d) { if (d.status !== 'DOWNLOADING') return d; const router = state.routers[d.routerId]; const active = router ? activeDownloads(router.id) : []; const count = Math.max(1, active.length); const speed = ((plan(state.subscriptions[router.ownerId]?.plan)?.downloadMbps || 0) * 1_000_000) / 8 / count; const elapsed = Math.max(0, Date.now() - d.lastUpdatedAt) / 1000; d.downloadedBytes = Math.min(d.totalBytes, d.downloadedBytes + Math.floor(speed * elapsed)); d.lastUpdatedAt = Date.now(); if (d.downloadedBytes >= d.totalBytes) { d.downloadedBytes = d.totalBytes; d.status = 'COMPLETED'; const pc = ensurePc(d.userId); pc.used += d.totalBytes; } return d; }
function disconnectRouter(routerId) { for (const d of Object.values(state.downloads)) { settle(d); if (d.routerId === routerId && d.status === 'DOWNLOADING') d.status = 'PAUSED'; } }
async function subscribe(userId, planId) { return mutate(async () => { const p = plan(planId); if (!p) return { error: 'plan' }; if (state.subscriptions[userId] && state.subscriptions[userId].expiresAt > Date.now()) return { error: 'active' }; const balance = await economy.getFishBalance(userId); if (balance < p.price) return { error: 'funds', price: p.price }; await economy.removeFish(userId, p.price); state.subscriptions[userId] = { userId, plan: planId, startedAt: Date.now(), expiresAt: Date.now() + 30 * 86400000 }; await save(); return { subscription: state.subscriptions[userId] }; }); }
async function cancel(userId) { return mutate(async () => { const s = state.subscriptions[userId]; if (!s) return false; s.cancelled = true; await save(); return true; }); }
async function router(userId) { return mutate(async () => { const sub = state.subscriptions[userId]; if (!sub || sub.expiresAt <= Date.now()) return null; if (!state.routers[userId]) state.routers[userId] = { id: userId, ownerId: userId, ssid: 'PikaPeng WiFi', visible: true, access: 'PUBLIC', passwordHash: null, allowlist: [], devices: {} }; await save(); return state.routers[userId]; }); }
async function setRouter(userId, changes) { return mutate(async () => { const r = state.routers[userId]; if (!r) return null; if (changes.ssid !== undefined) r.ssid = String(changes.ssid).slice(0, 64).replace(/@(everyone|here)/gi, '@ $1'); if (changes.visible !== undefined) r.visible = Boolean(changes.visible); if (changes.access) r.access = changes.access; if (changes.password !== undefined) r.passwordHash = changes.password ? crypto.createHash('sha256').update(changes.password).digest('hex') : null; await save(); return r; }); }
async function connect(userId, networkId, password) { return mutate(async () => { const r = Object.values(state.routers).find(x => x.id === networkId); if (!r || !onlineRouter(r) || (!r.visible && r.ownerId !== userId)) return { error: 'network' }; if (r.access === 'PASSWORD' && r.passwordHash !== crypto.createHash('sha256').update(String(password || '')).digest('hex')) return { error: 'password' }; if (r.access === 'FRIENDS_ONLY' && r.ownerId !== userId && !r.allowlist.includes(userId)) return { error: 'access' }; const p = ensurePc(userId); const sub = plan(state.subscriptions[r.ownerId].plan); if (!r.devices[userId] && Object.keys(r.devices).length >= sub.devices) return { error: 'limit' }; for (const d of Object.values(state.downloads)) { settle(d); if (d.userId === userId && d.status === 'DOWNLOADING') d.status = 'PAUSED'; } p.routerId = r.id; r.devices[userId] = { userId, connectedAt: Date.now() }; for (const d of Object.values(state.downloads)) if (d.userId === userId && d.status === 'PAUSED') { d.routerId = r.id; d.status = 'DOWNLOADING'; d.lastUpdatedAt = Date.now(); } await save(); return { router: r }; }); }
async function disconnect(userId) { return mutate(async () => { const p = ensurePc(userId); for (const d of Object.values(state.downloads)) { settle(d); if (d.userId === userId && d.status === 'DOWNLOADING') d.status = 'PAUSED'; } const r = p.routerId && state.routers[p.routerId]; if (r) delete r.devices[userId]; p.routerId = null; await save(); return true; }); }
async function networks() { await load(); return Object.values(state.routers).filter(r => r.visible && r.access === 'PUBLIC' && onlineRouter(r)).map(r => ({ id: r.id, ssid: r.ssid, ownerId: r.ownerId, plan: state.subscriptions[r.ownerId].plan, devices: Object.keys(r.devices).length })); }
async function kick(ownerId, userId) { return mutate(async () => { const r = state.routers[ownerId]; if (!r || r.ownerId !== ownerId) return false; delete r.devices[userId]; const p = ensurePc(userId); if (p.routerId === r.id) { for (const d of Object.values(state.downloads)) { settle(d); if (d.userId === userId && d.status === 'DOWNLOADING') d.status = 'PAUSED'; } p.routerId = null; } await save(); return true; }); }
async function download(userId, gameId) { return mutate(async () => { const game = GAMES[gameId]; const p = ensurePc(userId); const r = p.routerId && state.routers[p.routerId]; if (!game || !state.licenses[userId]?.includes(gameId)) return { error: 'license' }; if (!r || !onlineRouter(r)) return { error: 'network' }; settleExisting(userId); if (p.used + game.size > p.capacity) return { error: 'storage' }; const existing = Object.values(state.downloads).find(d => d.userId === userId && d.gameId === gameId && d.status !== 'FAILED'); if (existing) return { error: 'existing', download: existing }; const d = { id: crypto.randomUUID(), userId, gameId, totalBytes: game.size, downloadedBytes: 0, status: 'DOWNLOADING', lastUpdatedAt: Date.now(), routerId: r.id }; state.downloads[d.id] = d; await save(); return { download: d }; }); }
function settleExisting(userId) { for (const d of Object.values(state.downloads)) if (d.userId === userId) settle(d); }
async function license(userId, gameId) { return mutate(async () => { if (!GAMES[gameId]) return false; state.licenses[userId] ||= []; if (!state.licenses[userId].includes(gameId)) state.licenses[userId].push(gameId); await save(); return true; }); }
async function uninstall(userId, gameId) { return mutate(async () => { const d = Object.values(state.downloads).find(x => x.userId === userId && x.gameId === gameId && x.status === 'COMPLETED'); if (!d) return false; ensurePc(userId).used = Math.max(0, ensurePc(userId).used - d.totalBytes); delete state.downloads[d.id]; await save(); return true; }); }
async function fish(userId) { return mutate(async () => { const installed = Object.values(state.downloads).some(d => d.userId === userId && d.gameId === 'fish_simulator' && d.status === 'COMPLETED'); if (!installed) return { error: 'install' }; state.games[userId] ||= { caught: 0, species: [], rarest: null, cooldownAt: 0 }; if (state.games[userId].cooldownAt > Date.now()) return { error: 'cooldown', remaining: state.games[userId].cooldownAt - Date.now() }; const index = Math.floor(Math.random() ** 2 * SPECIES.length); const catchName = SPECIES[index]; const g = state.games[userId]; g.caught++; if (!g.species.includes(catchName)) g.species.push(catchName); g.rarest = index > (SPECIES.indexOf(g.rarest) || -1) ? catchName : g.rarest; g.cooldownAt = Date.now() + 30000; await save(); return { catchName, stats: g }; }); }
async function status(userId) { await load(); const p = ensurePc(userId); if (p.routerId) for (const d of Object.values(state.downloads)) if (d.userId === userId) { settle(d); if (!onlineRouter(state.routers[p.routerId]) && d.status === 'DOWNLOADING') d.status = 'PAUSED'; } return { subscription: state.subscriptions[userId], router: p.routerId ? state.routers[p.routerId] : null, pc: p, licenses: state.licenses[userId] || [], downloads: Object.values(state.downloads).filter(d => d.userId === userId), game: state.games[userId] || null }; }
module.exports = { PLANS, GAMES, GB, subscribe, cancel, router, setRouter, networks, connect, disconnect, kick, download, license, uninstall, fish, status, _resetForTests: async () => { state = { subscriptions: {}, routers: {}, pcs: {}, licenses: {}, downloads: {}, games: {} }; loaded = true; queue = Promise.resolve(); } };
