const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const economy = require('./economy');
const logger = require('./utils/logger');
const questions = require('./questions.json');
const storePath = path.join(__dirname, 'data', 'qotd-state.json');
let state = {}; let loaded = false; const locks = new Map();
async function load() { if (loaded) return; try { state = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { state = {}; } loaded = true; }
async function save() { await fs.writeFile(storePath, `${JSON.stringify(state, null, 2)}\n`, 'utf8'); }
function lock(id, task) { const p = (locks.get(id) || Promise.resolve()).then(task, task); locks.set(id, p); p.finally(() => locks.get(id) === p && locks.delete(id)).catch(() => {}); return p; }
function utcDate() { return new Date().toISOString().slice(0, 10); }
function get(id) { return state[id] || { enabled: false, channelId: null, daily: {}, history: [], attempts: {}, correct: {} }; }
function normalizeAnswer(value) { return String(value).trim().toLowerCase().replace(/\s+/g, ' '); }
const normalize = normalizeAnswer;
function choose(value) { const used = new Set(value.history || []); const fresh = questions.filter((q) => !used.has(q.id)); return (fresh.length ? fresh : questions)[crypto.randomInt(0, fresh.length || questions.length)]; }
async function configure(guildId, channelId) { await load(); return lock(guildId, async () => { const v = get(guildId); v.enabled = true; v.channelId = channelId; state[guildId] = v; await save(); return v; }); }
async function disable(guildId) { await load(); return lock(guildId, async () => { const v = get(guildId); v.enabled = false; state[guildId] = v; await save(); return v; }); }
async function post(client, guildId, rewardful = true) { await load(); return lock(guildId, async () => { const v = get(guildId); if (!v.channelId) return null; const day = utcDate(); if (rewardful && v.daily.date === day && v.daily.posted) return v.daily; const question = choose(v); const channel = await client.channels.fetch(v.channelId); const embed = { color: 0x6bd6e8, title: '🧠 Question of the Day', description: `${question.question}\n\n🐟 Reward: +${question.reward} Fish\n⏰ New question every day at 00:00 UTC`, footer: { text: 'PengBot · PikaStudio' } }; const message = await channel.send({ embeds: [embed], components: [{ type: 1, components: [{ type: 2, custom_id: `qotd_answer:${guildId}:${day}`, label: '🐧 Answer', style: 1 }] }] }); if (rewardful) { v.daily = { date: day, questionId: question.id, messageId: message.id, channelId: v.channelId, guildId, posted: true, attempts: 0, correct: 0 }; v.history = [...new Set([...(v.history || []), question.id])].slice(-questions.length); v.attempts[day] = {}; v.correct[day] = 0; state[guildId] = v; await save(); } return v.daily; }); }
async function answer(interaction, guildId, day, text) { await load(); return lock(guildId, async () => { const v = get(guildId); const d = v.daily; if (!d.posted || d.date !== day || d.guildId !== guildId) return { expired: true }; const key = `${day}:${interaction.user.id}`; if ((v.attempts[day] || {})[interaction.user.id]) return { attempted: true }; const q = questions.find((x) => x.id === d.questionId); if (!q) return { expired: true }; v.attempts[day] ||= {}; v.attempts[day][interaction.user.id] = { correct: false, at: new Date().toISOString() }; v.daily.attempts = (v.daily.attempts || 0) + 1; const correct = q.answers.some((a) => normalize(a) === normalize(text)); if (correct) { const reward = 100; try { const balance = await economy.addFish(interaction.user.id, reward); v.attempts[day][interaction.user.id] = { correct: true, rewarded: true, at: new Date().toISOString() }; v.daily.correct = (v.daily.correct || 0) + 1; v.correct[day] = v.daily.correct; state[guildId] = v; await save(); return { correct: true, reward, balance }; } catch (error) { delete v.attempts[day][interaction.user.id]; v.daily.attempts -= 1; logger.error('QOTD reward failed', error); throw error; } } state[guildId] = v; await save(); return { correct: false }; }); }
async function status(guildId) { await load(); return get(guildId); }
async function postTest(client, guildId, channelId) { await load(); return lock(guildId, async () => { const question = choose(get(guildId)); const channel = await client.channels.fetch(channelId); return channel.send({ embeds: [{ color: 0x6bd6e8, title: '🧠 Question of the Day · Test', description: `${question.question}\n\n🧪 Test question — no Fish reward\n⏰ Daily questions run at 00:00 UTC`, footer: { text: 'PengBot · PikaStudio' } }], components: [{ type: 1, components: [{ type: 2, custom_id: `qotd_test:${guildId}:${Date.now()}`, label: '🐧 Answer', style: 1, disabled: true }] }] }); }); }
module.exports = { configure, disable, post, postTest, answer, status, utcDate, normalizeAnswer };
