const fs = require('node:fs/promises'); const path = require('node:path'); const economy = require('./economy'); const config = require('./config'); const logger = require('./utils/logger');
const storePath = path.join(__dirname, 'data', 'ram-investments.json'); let records = {}; let loaded = false; let queue = Promise.resolve(); const PRICE_SCALE = 1000000;
function market() { const m = config.ramMarket(); if (!Number.isFinite(m.ddr5_8gb_price_ntd) || m.ddr5_8gb_price_ntd <= 0 || !Number.isFinite(m.salmon_100g_price_ntd) || m.salmon_100g_price_ntd <= 0 || !/^\d{4}-\d{2}-\d{2}$/.test(m.updated_at)) throw new Error('Invalid RAM market configuration.'); const ntdPerFish = m.salmon_100g_price_ntd / 100; const ramPerGbNtd = m.ddr5_8gb_price_ntd / 8; return { ...m, ntdPerFish, ramPerGbNtd, fishPerGb: ramPerGbNtd / ntdPerFish }; }
async function load() { if (loaded) return; try { records = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { records = {}; } loaded = true; } async function save() { await fs.writeFile(storePath, `${JSON.stringify(records, null, 2)}\n`, 'utf8'); }
const mutate = task => { const next = queue.then(task, task); queue = next.catch(() => {}); return next; }; const validGb = n => Number.isSafeInteger(n) && n > 0; const userRecord = id => records[id] ||= { userId: id, ramGb: 0, costBasisFish: 0, realizedProfitLossFish: 0 };
function charge(gb, m) { const value = gb * m.fishPerGb; const amount = Math.floor(value); if (!Number.isSafeInteger(amount) || amount < 1) throw new RangeError('RAM transaction exceeds safe Fish limits.'); return amount; }
async function get(userId) { await load(); return { ...(records[userId] || { userId, ramGb: 0, costBasisFish: 0, realizedProfitLossFish: 0 }) }; }
async function buy(userId, gb, theft) { if (!validGb(gb)) return { error: 'amount' }; if (await theft.hasActiveTheftAsThief(userId)) return { error: 'theft' }; return mutate(async () => { await load(); const m = market(); const amount = charge(gb, m); const r = userRecord(userId); const wallet = await economy.getFishBalance(userId); if (amount > wallet) return { error: 'funds', wallet, amount }; if (!Number.isSafeInteger(r.ramGb + gb) || !Number.isSafeInteger(r.costBasisFish + amount)) return { error: 'overflow' }; await economy.removeFish(userId, amount); const before = { ...r }; r.ramGb += gb; r.costBasisFish += amount; try { await save(); logger.info(`[RAM_BUY] user=${userId} gb=${gb} fish=${amount} marketFishPerGb=${m.fishPerGb} timestamp=${new Date().toISOString()}`); return { gb, amount, record: r, market: m }; } catch (e) { records[userId] = before; await economy.addFish(userId, amount); throw e; } }); }
async function sell(userId, gb) { if (!validGb(gb)) return { error: 'amount' }; return mutate(async () => { await load(); const m = market(); const amount = charge(gb, m); const r = userRecord(userId); if (gb > r.ramGb) return { error: 'holdings', holdings: r.ramGb }; const soldBasis = Math.floor(r.costBasisFish * gb / r.ramGb); const wallet = await economy.getFishBalance(userId); if (wallet > Number.MAX_SAFE_INTEGER - amount) return { error: 'overflow' }; await economy.addFish(userId, amount); const before = { ...r }; r.ramGb -= gb; r.costBasisFish -= soldBasis; r.realizedProfitLossFish += amount - soldBasis; try { await save(); logger.info(`[RAM_SELL] user=${userId} gb=${gb} fish=${amount} marketFishPerGb=${m.fishPerGb} timestamp=${new Date().toISOString()}`); return { gb, amount, record: r, market: m }; } catch (e) { records[userId] = before; await economy.removeFish(userId, amount); throw e; } }); }
module.exports = { get, buy, sell, market, charge, validGb };
