const fs = require('node:fs/promises'); const path = require('node:path'); const crypto = require('node:crypto'); const economy = require('./economy'); const config = require('./config'); const logger = require('./utils/logger');
const storePath = path.join(__dirname, 'data', 'shops.json'); let state = { shops: {}, orders: {} }; let loaded = false; let queue = Promise.resolve();
const mutate = task => { const next = queue.then(task, task); queue = next.catch(() => {}); return next; }; async function load() { if (loaded) return; try { state = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch {} state.shops ||= {}; state.orders ||= {}; loaded = true; } async function save() { await fs.writeFile(storePath, `${JSON.stringify(state, null, 2)}\n`, 'utf8'); }
const clean = s => s.trim().replace(/[\r\n]/g, ' ').replace(/\s+/g, ' '); const safe = n => Number.isSafeInteger(n) && n > 0; const shopOf = (g, u) => Object.values(state.shops).find(s => s.guildId === g && s.ownerId === u && s.status !== 'REMOVED'); const code = () => { const a = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; let x = ''; for (let i = 0; i < 10; i++) x += a[crypto.randomInt(a.length)]; return `PK-${x.slice(0, 5)}-${x.slice(5)}`; }; const hash = c => crypto.createHash('sha256').update(c).digest('hex');
async function create(guildId, userId, name) { return mutate(async () => { await load(); if (shopOf(guildId, userId)) return { error: 'owned' }; const n = clean(name); const cost = config.shopCreateCost(); if (n.length < 2 || n.length > 60) return { error: 'name' }; const wallet = await economy.getFishBalance(userId); if (wallet < cost) return { error: 'funds', wallet, cost }; await economy.removeFish(userId, cost); const shop = { shopId: crypto.randomUUID(), guildId, ownerId: userId, name: n, description: '', status: 'ACTIVE', products: {}, createdAt: Date.now() }; state.shops[shop.shopId] = shop; try { await save(); logger.info(`[SHOP_CREATE] shop=${shop.shopId} owner=${userId} cost=${cost}`); return { shop }; } catch (e) { delete state.shops[shop.shopId]; await economy.addFish(userId, cost); throw e; } }); }
async function productCreate(g, u, name, price, description) { return mutate(async () => { await load(); const s = shopOf(g, u); const n = clean(name); const d = clean(description || ''); if (!s || s.status !== 'ACTIVE' || n.length < 2 || n.length > 80 || d.length > 500 || !safe(price) || price > config.shopMaxProductPrice()) return { error: 'invalid' }; if (Object.keys(s.products).length >= config.shopMaxProducts()) return { error: 'limit' }; const p = { productId: crypto.randomUUID(), shopId: s.shopId, name: n, description: d, priceFish: price, active: true, createdAt: Date.now() }; s.products[p.productId] = p; await save(); return { product: p, shop: s }; }); }
async function findShop(g, id) { await load(); return Object.values(state.shops).find(s => s.guildId === g && (s.shopId === id || s.name.toLowerCase() === String(id).toLowerCase()) && s.status !== 'REMOVED'); }
async function buy(g, b, shopId, productId, quantity, theft) { if (!safe(quantity) || quantity > config.shopMaxQuantity()) return { error: 'quantity' }; if (await theft.hasActiveTheftAsThief(b)) return { error: 'theft' }; return mutate(async () => { await load(); const s = await findShop(g, shopId); if (!s || s.status !== 'ACTIVE') return { error: 'shop' }; if (s.ownerId === b) return { error: 'own' }; const p = s.products[productId]; if (!p?.active) return { error: 'product' }; const total = p.priceFish * quantity; if (!Number.isSafeInteger(total)) return { error: 'overflow' }; const wallet = await economy.getFishBalance(b); if (wallet < total) return { error: 'funds', wallet, total }; const pickupCode = code(); const o = { orderId: crypto.randomUUID(), guildId: g, shopId: s.shopId, sellerId: s.ownerId, buyerId: b, productSnapshot: { productId: p.productId, name: p.name, unitPriceFish: p.priceFish }, quantity, totalFish: total, escrowFish: total, status: 'PENDING', codeHash: hash(pickupCode), createdAt: Date.now(), fulfilledAt: null, cancelledAt: null }; await economy.removeFish(b, total); state.orders[o.orderId] = o; try { await save(); return { order: o, pickupCode }; } catch (e) { delete state.orders[o.orderId]; await economy.addFish(b, total); throw e; } }); }
async function validate(g, actor, pickup) { return mutate(async () => { await load(); const o = Object.values(state.orders).find(x => x.guildId === g && x.status === 'PENDING' && hash(pickup) === x.codeHash); if (!o) return { error: 'invalid' }; const s = state.shops[o.shopId]; if (!s || s.status !== 'ACTIVE' || s.ownerId !== actor) return { error: 'permission' }; await economy.addFish(o.sellerId, o.escrowFish); o.status = 'FULFILLED'; o.fulfilledAt = Date.now(); o.escrowFish = 0; await save(); logger.info(`[SHOP_ORDER_FULFILLED] order=${o.orderId} shop=${o.shopId} amount=${o.totalFish}`); return { order: o }; }); }
async function cancel(g, buyer, id) { return mutate(async () => { await load(); const o = state.orders[id]; if (!o || o.guildId !== g || o.buyerId !== buyer || o.status !== 'PENDING') return { error: 'invalid' }; await economy.addFish(buyer, o.escrowFish); o.status = 'CANCELLED'; o.cancelledAt = Date.now(); o.escrowFish = 0; await save(); return { order: o }; }); }
async function moderate(g, id, admin, action, reason) { return mutate(async () => { await load(); const s = await findShop(g, id); if (!s) return { error: 'shop' }; if (action === 'restore' && s.status !== 'SUSPENDED') return { error: 'state' }; if (action === 'suspend' && s.status !== 'ACTIVE') return { error: 'state' }; s.status = action === 'remove' ? 'REMOVED' : action === 'suspend' ? 'SUSPENDED' : 'ACTIVE'; s.moderation = { action, adminId: admin, reason: clean(reason || ''), at: Date.now() }; let refunded = 0; if (action === 'remove') for (const o of Object.values(state.orders)) if (o.shopId === s.shopId && o.status === 'PENDING') { await economy.addFish(o.buyerId, o.escrowFish); refunded += o.escrowFish; o.status = 'CANCELLED'; o.cancelledAt = Date.now(); o.escrowFish = 0; } for (const p of Object.values(s.products)) if (action !== 'restore') p.active = false; await save(); logger.info(`[SHOP_${action.toUpperCase()}] shop=${s.shopId} admin=${admin} reason=${JSON.stringify(reason || '')}`); return { shop: s, refunded }; }); }
async function browse(g) { await load(); return Object.values(state.shops).filter(s => s.guildId === g && s.status === 'ACTIVE'); }
async function orders(g, u) { await load(); return Object.values(state.orders).filter(o => o.guildId === g && (o.sellerId === u || o.buyerId === u)); } module.exports = { create, productCreate, findShop, browse, buy, validate, cancel, moderate, orders };
