const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const storePath = path.join(__dirname, 'data', 'travel.json');
let state; let queue = Promise.resolve();
async function load() { if (state) return state; try { state = JSON.parse(await fs.readFile(storePath, 'utf8')); } catch { state = { destinations: [], passports: {} }; } state.destinations ||= []; state.passports ||= {}; return state; }
async function save() { const tmp = `${storePath}.tmp`; await fs.writeFile(tmp, `${JSON.stringify(state, null, 2)}\n`, 'utf8'); await fs.rename(tmp, storePath); }
function mutate(fn) { const next = queue.then(fn, fn); queue = next.catch(() => {}); return next; }
function validGuildId(id) { return /^\d{17,20}$/.test(String(id)); }
function validInvite(url) { try { const parsed = new URL(url); return parsed.protocol === 'https:' && (parsed.hostname === 'discord.gg' || parsed.hostname === 'discord.com' || parsed.hostname === 'discordapp.com'); } catch { return false; } }
async function list(all = true) { await load(); return state.destinations.filter((d) => all || d.enabled); }
async function add(destination) { return mutate(async () => { await load(); if (!validGuildId(destination.guildId)) throw new Error('Invalid guild ID.'); if (state.destinations.some((d) => d.guildId === destination.guildId)) throw new Error('Guild is already registered.'); if (!destination.name?.trim()) throw new Error('Server name is required.'); if (!validInvite(destination.invite)) throw new Error('Invite must be a valid Discord invite URL.'); const item = { id: crypto.randomBytes(8).toString('hex'), name: destination.name.trim().slice(0, 100), guildId: destination.guildId, invite: destination.invite.trim(), description: String(destination.description || '').trim().slice(0, 500), stamp: String(destination.stamp || '').trim().slice(0, 80), region: String(destination.region || '').trim().slice(0, 80), enabled: true, createdAt: new Date().toISOString() }; state.destinations.push(item); await save(); return item; }); }
async function update(guildId, changes) { return mutate(async () => { await load(); const item = state.destinations.find((d) => d.guildId === guildId); if (!item) throw new Error('Destination not found.'); Object.assign(item, changes); if (changes.invite && !validInvite(item.invite)) throw new Error('Invalid invite URL.'); await save(); return item; }); }
async function remove(guildId) { return mutate(async () => { await load(); state.destinations = state.destinations.filter((d) => d.guildId !== guildId); await save(); }); }
async function choose(client, userId, currentGuildId) { const choices = (await list(false)).filter((d) => d.guildId !== currentGuildId); const available = []; for (const destination of choices) { const guild = await client.guilds.fetch(destination.guildId).catch(() => null); if (!guild) { available.push(destination); continue; } const member = await guild.members.fetch(userId).catch(() => null); if (!member) available.push(destination); } return available[Math.floor(Math.random() * available.length)] || null; }
async function recordVisit(userId, destination) { return mutate(async () => { await load(); state.passports[userId] ||= {}; const old = state.passports[userId][destination.guildId] || { guildId: destination.guildId, firstVisitAt: new Date().toISOString(), visitCount: 0, stamp: destination.stamp, name: destination.name }; old.visitCount += 1; state.passports[userId][destination.guildId] = old; await save(); return old; }); }
module.exports = { list, add, update, remove, choose, recordVisit, validGuildId, validInvite };
