const fs = require('node:fs/promises'); const path = require('node:path');
const { EmbedBuilder } = require('discord.js'); const economy = require('./economy'); const config = require('./config'); const logger = require('./utils/logger'); const { encode, isUsable } = require('./pika-screaming');
const cachePath = path.join(__dirname, 'data', 'waddle-race-sentences.json');
const MIN = config.waddleRaceMinIntervalMs(); const MAX = config.waddleRaceMaxIntervalMs(); const MAX_ANSWER = config.waddleRaceMaxAnswerLength();
let cache = []; let loaded = false; let timer = null; let running = false; let active = null; let activityAt = 0;
async function load() { if (loaded) return; try { cache = JSON.parse(await fs.readFile(cachePath, 'utf8')); } catch { cache = []; } loaded = true; }
async function save() { await fs.mkdir(path.dirname(cachePath), { recursive: true }); await fs.writeFile(cachePath, `${JSON.stringify(cache.slice(-50), null, 2)}\n`); }
function randomDelay() { return MIN + Math.floor(Math.random() * (MAX - MIN + 1)); }
function recordActivity(message) { if (!message?.guildId || !message.channelId || message.author?.bot || message.webhookId) return false; if (message.channelId !== config.typeraceChannelId()) return false; activityAt = Date.now(); return true; }
function recentActivity() { return activityAt > 0 && Date.now() - activityAt <= config.waddleRaceActivityWindowMs(); }
function firstMismatch(a, b) { const length = Math.min(a.length, b.length); for (let i = 0; i < length; i++) if (a[i] !== b[i]) return i; return a.length === b.length ? -1 : length; }
function normalizeSubmitted(value) { return String(value ?? '').replace(/\r\n/g, '\n').replace(/\n/g, ''); }
async function fetchSentence() { const url = 'https://en.wikipedia.org/w/api.php?action=query&generator=random&grnnamespace=0&grnlimit=8&prop=extracts|info&inprop=url&explaintext=1&format=json'; const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 7000); try { const response = await fetch(url, { signal: controller.signal, headers: { 'User-Agent': 'IglooBot/1.0 (WaddleRace; contact configured bot administrator)' } }); if (!response.ok) throw new Error(`Wikimedia HTTP ${response.status}`); const json = await response.json(); for (const page of Object.values(json.query?.pages || {})) { const source = page.extract?.split(/(?<=[.!?])\s+/).find(s => isUsable(s, MAX_ANSWER)); if (source) return { text: source.trim(), title: page.title, url: page.fullurl }; } } finally { clearTimeout(timeout); } return null; }
async function sentence() { await load(); for (let i = 0; i < 2; i++) { try { const result = await fetchSentence(); if (result) { cache.push(result); await save(); return result; } } catch (error) { logger.error('WaddleRace Wikimedia fetch failed', error); } } const fallback = cache.filter(x => isUsable(x.text, MAX_ANSWER)); if (!fallback.length) throw new Error('No valid Wikimedia sentence is available.'); return fallback[Math.floor(Math.random() * fallback.length)]; }
async function startRace(client, { bypassActivityCheck = false } = {}) { if (active || (!bypassActivityCheck && !recentActivity())) return false; const channel = await client.channels.fetch(config.typeraceChannelId()).catch(() => null); if (!channel?.isTextBased()) return false; const prompt = await sentence(); const expected = encode(prompt.text); const started = process.hrtime.bigint(); const message = await channel.send({ embeds: [new EmbedBuilder().setColor(0x6bd6e8).setTitle(`${config.pengEmoji()} WADDLE RACE`).setDescription(`Translate this into PikaPengScreamingLang:\n\n**${prompt.text}**\n\nFirst correct answer wins!`)] }); active = { expected, started, channelId: channel.id, source: prompt, message, won: false }; logger.info('WaddleRace started successfully'); return true; }
async function attempt(client, options = {}) { if (!running) return; try { if (!active) await startRace(client, options); } catch (error) { logger.error('WaddleRace attempt failed', error); } finally { if (running) timer = setTimeout(() => attempt(client, { bypassActivityCheck: false }), randomDelay()); timer?.unref?.(); } }
async function start(client) { if (running) return false; running = true; await load(); logger.info('WaddleRace scheduler started'); logger.info('WaddleRace startup race triggered'); await attempt(client, { bypassActivityCheck: true }); return true; }
async function stop() { if (timer) clearTimeout(timer); timer = null; running = false; active = null; }
async function handleMessage(message) { logger.info(`WaddleRace message received: user=${message.author.id} channel=${message.channel?.id || message.channelId} active=${Boolean(active)} length=${message.content.length}`); recordActivity(message); if (!active || active.won || message.channelId !== active.channelId || message.author?.bot || message.webhookId) return false; const submitted = normalizeSubmitted(message.content); const race = active; const match = submitted === race.expected; logger.info(`WaddleRace attempt received: user=${message.author.id} channel=${message.channel?.id || message.channelId} active=true submittedLength=${submitted.length} expectedLength=${race.expected.length} match=${match} firstMismatch=${firstMismatch(submitted, race.expected)}`); if (!match) { try { await message.react('❌'); } catch (error) { logger.error(`WaddleRace incorrect-answer reaction failed: ${error.message}`); } return false; } race.won = true; active = null; const elapsed = Number(process.hrtime.bigint() - race.started) / 1e9; try { const balance = await economy.addFish(message.author.id, config.waddleRaceReward()); await race.message.channel.send(`${config.pengEmoji()} **WADDLE RACE COMPLETE!**\n\n🏆 <@${message.author.id}> translated the scream correctly!\n🐟 +${config.waddleRaceReward()} Fish\n\nTime: **${elapsed.toFixed(2)} seconds**\nSource: [${race.source.title}](${race.source.url})`); logger.info(`WaddleRace winner handled: user=${message.author.id} balance=${balance}`); } catch (error) { logger.error(`WaddleRace winner handling failed: ${error.message}`); } return true; }
async function startNow(client) { return startRace(client, { bypassActivityCheck: true }); }
module.exports = { encode, firstMismatch, normalizeSubmitted, start, stop, handleMessage, recordActivity, startNow, isRunning: () => running, getActive: () => active, _resetForTests: async () => { await stop(); cache = []; loaded = true; activityAt = 0; } };
