const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const economy = require('./economy');

const statePath = path.join(__dirname, 'data', 'work-state.json');
const WORK_COOLDOWN_MS = 30 * 60 * 1000;
const OUTCOME_WEIGHTS = { normal: 70, great: 20, failure: 8, rare: 2 };
const REWARDS = { normal: [8, 20], great: [20, 40], failure: [0, 5], rare: [40, 100] };
const RARE_MESSAGES = ['You fixed DNS on the first try. This has never happened before.', 'You opened the server rack and found a fish inside. Nobody knows how long it has been there.', 'The NAS stopped responding. You turned it off and back on again. PikaPeng has promoted you to Senior Button Presser.'];
const jobs = [
  ['Repairing the igloo server rack', 'The server rack is standing again, mostly.'], ['Labeling mysterious ethernet cables', 'You labeled 47 ethernet cables in the igloo server room.'], ['Shoveling snow away from the datacenter', 'You cleared a heroic path through the snow.'], ['Debugging the fish database', 'You fixed three bugs and only created one new mystery.'], ['Replacing a frozen SSD', 'You replaced the SSD before it became a decorative ice cube.'], ['Restarting a suspicious server', 'You turned the suspicious server off and on again.'], ["Cleaning PikaPeng's keyboard", 'You removed enough crumbs to reveal the original key layout.'], ['Updating the igloo firewall', 'You blocked several suspicious snowballs.'], ['Delivering fish to another department', 'You delivered the fish without losing even one to quality control.'], ['Fixing the Wi-Fi antenna', 'You pointed the antenna toward the strongest possible signal.'], ['Organizing backup drives', 'You organized the backup drives by date, size, and vibes.'], ['Reviewing extremely questionable logs', 'You reviewed the logs and found the suspicious login was PikaPeng.'], ['Installing updates on an ancient computer', 'You installed the updates without waking the ancient computer.'], ['Recovering a server after PikaPeng unplugged it', 'You recovered the server and located the very obvious power cable.'], ['Removing snow from the NAS', 'You cleared the NAS vents and restored its chilly dignity.'], ['Testing the emergency fish supply', 'You confirmed the emergency fish supply still exists.'], ['Finding the cable nobody remembers installing', 'You found the cable and wisely chose not to ask where it goes.'], ['Restarting DNS and hoping for the best', 'You restarted DNS and hoped with professional confidence.'], ['Investigating why CPU usage is 100%', 'You found the process consuming all the CPU: it was "penguin.exe".'], ['Turning something off and back on again', 'You turned something off and back on again. It worked.'],
].map(([title, message], index) => ({ id: `job-${index + 1}`, title, messages: [message] }));
let records = {}; let loaded = false; let saveQueue = Promise.resolve(); const locks = new Map();
async function load() { if (loaded) return; try { records = JSON.parse(await fs.readFile(statePath, 'utf8')); } catch { records = {}; } loaded = true; }
async function save() { saveQueue = saveQueue.then(() => fs.writeFile(statePath, `${JSON.stringify(records, null, 2)}\n`, 'utf8')); return saveQueue; }
function withLock(id, task) { const previous = locks.get(id) || Promise.resolve(); const current = previous.then(task, task); locks.set(id, current); current.finally(() => { if (locks.get(id) === current) locks.delete(id); }).catch(() => {}); return current; }
function random(list) { return list[crypto.randomInt(list.length)]; }
function rewardFor(outcome) { const [min, max] = REWARDS[outcome]; return min + crypto.randomInt(max - min + 1); }
function chooseOutcome() { const roll = crypto.randomInt(100); let threshold = 0; for (const [outcome, weight] of Object.entries(OUTCOME_WEIGHTS)) { threshold += weight; if (roll < threshold) return outcome; } return 'normal'; }
async function performWork(userId) { return withLock(userId, async () => { await load(); const previous = { ...(records[userId] || {}) }; const now = Date.now(); const last = Number.isFinite(previous.lastWorkAt) ? previous.lastWorkAt : 0; if (now < last + WORK_COOLDOWN_MS) return { onCooldown: true, nextWorkAt: last + WORK_COOLDOWN_MS }; const choices = jobs.filter((job) => job.id !== previous.lastWorkJob); const job = random(choices.length ? choices : jobs); const outcome = chooseOutcome(); const reward = rewardFor(outcome); let balance; try { balance = await economy.addFish(userId, reward); records[userId] = { lastWorkAt: now, totalWorkShifts: (Number.isSafeInteger(previous.totalWorkShifts) ? previous.totalWorkShifts : 0) + 1, lastWorkJob: job.id }; await save(); } catch (error) { records[userId] = previous; if (reward > 0 && balance !== undefined) await economy.removeFish(userId, reward).catch(() => {}); throw error; } return { onCooldown: false, nextWorkAt: now + WORK_COOLDOWN_MS, job, outcome, reward, message: outcome === 'rare' ? random(RARE_MESSAGES) : job.messages[0], balance, totalWorkShifts: records[userId].totalWorkShifts }; }); }
async function getWorkStats(userId) { await load(); const record = records[userId] || {}; return { totalWorkShifts: Number.isSafeInteger(record.totalWorkShifts) ? record.totalWorkShifts : 0 }; }
module.exports = { performWork, getWorkStats, WORK_COOLDOWN_MS, OUTCOME_WEIGHTS, REWARDS, jobs };
